[MRG] Fixing scans check to make sure BTI and CTF data work (directory based files for MEG)
bids-standard/legacy-validator pull request #1005
Opened 2020-06-26 00:49 UTC by adam2392

Closes: #1002 

I'm not an  expert w/ MEG data, and I don't even work with it, but there was a related issue with the validator issuing an error in `mne-bids` when writing BTI and CTF data. I updated the unit tests and the validator on `scans.tsv` to account for this behavior.

2020-06-28 15:32 UTC, adam2392 commented
Any update on this being mergable?

2020-06-28 16:15 UTC, sappelhoff commented
> Any update on this being mergable?

Let's wait until it's a weekday again. I hope that @rwblair or @nellh can have a look and judge it.

2020-06-28 19:46 UTC, nellh requested changes
Functional change here looks good to me, just some minor code quality improvements requested. The path module question I'll file as a new issue for since there are examples of it prior to this and #976, I don't think it should block this.

2020-06-28 19:46 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
> +          var fDir = String(path.dirname(fPath))
The String constructor here should be redundant, is there a reason it's needed?

2020-06-28 19:46 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
> +    const scanDirPath = path.dirname(file.relativePath)
I like using the path module for path manipulation more, we have a lot of manual path manipulation around the validator that is error prone. I wrote some comments in https://github.com/bids-standard/bids-validator/pull/976#pullrequestreview-438795376 about some possible issues with it.

2020-06-28 19:46 UTC, nellh commented on bids-validator/tests/tsv.spec.js
> +    var scansNoSesFile = {
There's no reason for any of the `var` usage in this PR, we should replace it with `const` to be consistent. A lot of the older validator code was written for early versions of Node.js where var was the only option but we've long since dropped support for those versions of Node.

2020-06-28 19:46 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
>      for (let f in fileList) {
This is from #976 but this should be `for ... of Array.from(fileList)` to avoid bugs if fileList has properties that are not files.

2020-06-28 20:33 UTC, adam2392 commented on bids-validator/validators/tsv/tsv.js
> +    const scanDirPath = path.dirname(file.relativePath)
Not sure what you mean here. I'm reading that this is preliminarily okay, but will get addressed in the issue #1007 ?

2020-06-28 20:39 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
> +    const scanDirPath = path.dirname(file.relativePath)
Yes, I thought it may have been introduced by #976 but the path module usage predates that PR and #1007 is a better place to address the issue.

2020-06-28 21:08 UTC, adam2392 commented
I'm not sure why the `cli.js` is failing :(

2020-06-28 21:30 UTC, nellh commented
> I'm not sure why the `cli.js` is failing :(

It's because the tests/data/valid_dataset example dataset used in the CLI fails this test with an error now and I gave you some bad advice... Sorry about that, this isn't a FileList, it is actually an object with properties for each file under NodeJS.

This should fix things for both environments.

```javascript
    // get list of file paths for this subject and session
    const pathList = []
    for (let file of Object.values(fileList)) {
```

2020-06-29 16:48 UTC, rwblair approved these changes

2020-06-29 17:04 UTC, nellh approved these changes

2020-06-29 17:28 UTC, merged