Allow datasets to specify HED versions or individual files
bids-standard/legacy-validator pull request #1015
Opened 2020-07-15 16:41 UTC by happy5214

This implements the changes proposed in https://github.com/bids-standard/bids-specification/pull/527 to allow datasets to specify their HED schema version, or a specific schema file in sourcedata/, to run HED validation against. I have tested both ways with a sample dataset.

2020-07-17 16:40 UTC, sappelhoff requested changes
Thanks @happy5214. I'll leave a full review of this to @rwblair ... and we should also probably wait with merging this until the PR https://github.com/bids-standard/bids-specification/pull/527 is merged.

But I'll leave a few comments:

- You need to update https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/schemas/dataset_description.json so that it includes `HEDVersion`
- in https://github.com/bids-standard/bids-specification/pull/527 we are discussing that `HEDVersion` should be a *recommended* field. So perhaps it'd be nice to make BIDS-validator *warn* users if they are using HED tags ... but not supplying an `HEDVersion` field.
- I think we should have a *very basic* example dataset with HED tags in https://github.com/bids-standard/bids-examples/ ... it could be as simple as a single subject single session EEG ... with HED tags in the events.json. One idea could be to update https://github.com/bids-standard/bids-examples/tree/master/eeg_matchingpennies which is a very basic example.


edit: tagging @VisLab for attention

2020-07-27 14:06 UTC, happy5214 commented
> Thanks @happy5214. I'll leave a full review of this to @rwblair ... and we should also probably wait with merging this until the PR [bids-standard/bids-specification#527](https://github.com/bids-standard/bids-specification/pull/527) is merged.
> 
> But I'll leave a few comments:
> 
>     * You need to update https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/schemas/dataset_description.json so that it includes `HEDVersion`
> 
>     * in [bids-standard/bids-specification#527](https://github.com/bids-standard/bids-specification/pull/527) we are discussing that `HEDVersion` should be a _recommended_ field. So perhaps it'd be nice to make BIDS-validator _warn_ users if they are using HED tags ... but not supplying an `HEDVersion` field.
> 
>     * I think we should have a _very basic_ example dataset with HED tags in https://github.com/bids-standard/bids-examples/ ... it could be as simple as a single subject single session EEG ... with HED tags in the events.json. One idea could be to update https://github.com/bids-standard/bids-examples/tree/master/eeg_matchingpennies which is a very basic example.
> 
> 
> edit: tagging @VisLab for attention

The issues listed have been addressed (or will be after https://github.com/bids-standard/bids-examples/pull/191 is merged). I left in the local schema code for now, but I can remove it if anyone has a strong opinion on that.

2020-07-31 15:55 UTC, happy5214 commented
Is this waiting on the example dataset? That will probably take a while to finish, so perhaps we should merge this first.

2020-07-31 16:53 UTC, sappelhoff commented
It'd be cool to give @rwblair some more time to review this - and I think bids-standard/bids-specification#527 should be merged first once discussion is done over there.

2020-08-04 21:40 UTC, rwblair requested changes

2020-08-04 21:40 UTC, rwblair commented on bids-validator/validators/events/hed.js
> +    return hedValidator.buildSchema(schemaDefinition).then(hedSchema => {
I'm ok with leaving in the local schema ability, can we add a catch statement on this promise chain? If `HEDVersion` is not a semantic version and the file doesn't exist it produces an uncaught error. I think generating  a new issue here would be good. I figure most end users will have mistyped the semantic version rather than be trying to use their own schema.

I think the catch is also good in case the hed validator ever rejects its promise during build schema for whatever reason: https://github.com/hed-standard/hed-javascript/blob/f9674dfc6a18ec068260559b6d485b6ca61d0298/validators/schema.js#L374

2020-08-04 21:41 UTC, rwblair commented on bids-validator/validators/events/hed.js
> +    return hedValidator.buildSchema(schemaDefinition).then(hedSchema => {
Sorry I didn't realize that I had left this unsubmitted @happy5214 I'm going to go ahead and fix the merge conflict and merge this, and create a new issue for my concern here.

2020-08-04 21:56 UTC, merged