run 'npm audit fix' in ./bids-validator
bids-standard/legacy-validator pull request #1187
Opened 2021-02-13 07:52 UTC by sappelhoff

Trying to address some of the security concerns.

I simply navigated to `./bids-validator` and ran `npm audit fix`

maybe related: #1106

2021-03-01 15:27 UTC, sappelhoff commented
@rwblair did you also `cd` into the subdirs and just added `force` to the command? or did you do something else?

Also, this does not seem to fix the deprecation warnings - but perhaps at least the security issues?
(see: https://app.circleci.com/pipelines/github/bids-standard/bids-validator/660/workflows/3eaf4182-90ef-456b-b8ec-568d83ccc82f/jobs/7598 ... and screenshot below)

![image](https://user-images.githubusercontent.com/9084751/109518782-dfa39200-7aaa-11eb-8854-10853769bf45.png)



also, Ross did you see: https://github.com/bids-standard/bids-validator/issues/1106#issuecomment-783377429 ?

2021-03-01 15:49 UTC, rwblair commented
Yeah ran the audit cd'd into the directory. As far as my lerna/npm concerns as long as the package.json is getting updated it should be good to go.

Looking at #1106.

2021-03-01 22:26 UTC, rwblair commented
So my last commit 8c37da4 does quite a few things and we may revert.

The lerna configuration wasn't setup to use yarn, so I removed the yarn.lock and updated documentation to use npm solely.

Running npm install in the root directory should take care of the linking for bids-validator and bids-validator-web. At this point lerna is only being used to manage the semver for package.json files.

Something in the last batch of upgrades broke hed tests so I'll try and fix those.

I'll also update contributing documentation with state of tooling and note npm 7+ as a requirement.

2021-03-01 22:41 UTC, nellh requested changes
@rwblair This looks pretty good to me. Requiring npm 7 for development seems fine, it should still run on npm 6 or yarn 1.7.0+

2021-03-01 22:41 UTC, nellh commented on package.json
> +    "web-export": "npm web-build && cd bids-validator-web && npm next export"
These need to be `npm run ...`  for any scripts being called, the shorthand only works for `npm start`.

2021-03-02 08:43 UTC, sappelhoff reviewed
so does this now supersede #1102?

2021-03-02 08:43 UTC, sappelhoff commented on bids-validator-code.code-workspace
> -}
what was this file for?

2021-03-02 08:43 UTC, sappelhoff commented on bids-validator/package.json
> +    "bids-validator": "bin/bids-validator"
was this an automatic change? or is there some deliberate reasoning to it?

2021-03-02 08:43 UTC, sappelhoff commented on bids-validator/package.json
> -    "lerna": "^3.15.0",
did you remove this manually? I get confused with what gets auto-updated through things like "npm audit fix", and what gets manually removed.

Also I thought we'd still need lerna for the publishing flow?

explanations would be highly appreciated, so I can be of more help in the future! :)

2021-03-02 13:38 UTC, rwblair commented on bids-validator-code.code-workspace
> -}
Looks like it was a visual studio code specific file that snuck through some how.

2021-03-02 13:43 UTC, rwblair commented on bids-validator/package.json
> -    "lerna": "^3.15.0",
That I removed manually, it was causing a number of the deprecation warnings.

Lerna is only a dev dependency of the root project, not necessary for the bids-validator package that we publish to NPM to work.

2021-03-02 13:46 UTC, rwblair commented on bids-validator/package.json
> +    "bids-validator": "bin/bids-validator"
I believe that was automatic, not sure what package.json thinks about relative paths with and without dot slash. If in the end the tests pass on CI and locally I won't worry about it.

2021-03-02 13:48 UTC, rwblair commented
> so does this now supersede #1102?

Sorry to hijack your PR, the deprecation warning issue lead me down a rabbit hole, and this PR was newer cleaner than my old branch. I went ahead and closed #1102.

2021-03-02 14:11 UTC, sappelhoff commented on bids-validator/package.json
> -    "lerna": "^3.15.0",
Ahh I see, thanks. perhaps we should also take the chance to bump `"lerna": "^3.15.0"` for 3.22.1 (see https://github.com/bids-standard/bids-validator/issues/1106#issuecomment-783377429)

2021-03-02 14:11 UTC, sappelhoff commented on bids-validator/package.json
> +    "bids-validator": "bin/bids-validator"
fair enough, thanks!

2021-03-02 17:33 UTC, rwblair commented
@happy5214 I'm seeing an invalid place holder error show up in the hed tests, Is this something the bids-validator is doing wrong?

2021-03-02 22:13 UTC, happy5214 commented
> ~@happy5214 I'm seeing an invalid place holder error show up in the hed tests, Is this something the bids-validator is doing wrong?~
> 
> Looks like this is generated from hed-validator 3.0.3. For this PR I'll pin to 3.0.2
> 
> https://circleci.com/api/v1.1/project/github/bids-standard/bids-validator/7630/output/107/0?file=true&allocation-id=603d73fd600d152d2f0a5cd3-0-build%2F7603ED53

It is in fact an error with the bids-validator testcase for that issue code. The hed-validator code was fixed in that version to only pass placeholder tags (ones with `#`) in tags with the `takesValue` attribute, which that tag does not. The previous behavior (in 3.0.2) was in fact a bug. I can post a PR with an updated test string.

2021-03-03 08:25 UTC, sappelhoff commented on bids-validator/package.json
> +    "hed-validator": "3.0.2",
after @happy5214's fix, this can probably be `^3.0.0` again

2021-03-03 08:29 UTC, sappelhoff commented on bids-validator/package.json
> +    "hed-validator": "3.0.2",
```suggestion
    "hed-validator": "^3.0.0",
```

2021-03-03 08:34 UTC, sappelhoff commented
bumping the hed-validator version up again did fix some issues.

The remaining ones are mostly due to:

> Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

whatever that is.

2021-03-03 16:22 UTC, nellh commented
> bumping the hed-validator version up again did fix some issues.
> 
> The remaining ones are mostly due to:
> 
> > Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
> 
> whatever that is.

That timeout can be two kinds of failures, one is that CI is throttled so these tests finish but they take longer than the 5 second cutoff. The timeout can be raised by passing milliseconds as the third argument to it(). The other is that the promise never resolves and that's a legitimate bug.

2021-03-03 16:31 UTC, sappelhoff commented
running `npm test` on a fresh local installation (`npm install` after `rm -rf node_modules`) of this PR passes. :thinking: 

I noticed that in the CI, there is also one non-timeout related error (see screenshot below)  -  but that one passes locally as well.

![image](https://user-images.githubusercontent.com/9084751/109838280-4d37f580-7c46-11eb-875b-aab8539b97ed.png)

2021-03-04 09:15 UTC, sappelhoff commented on .circleci/config.yml
> +          command: npm run coverage --maxWorkers=2
```suggestion
          command: npm run coverage --maxWorkers=2 --testTimeout= 10000
```

2021-03-04 09:35 UTC, sappelhoff commented
@nellh @rwblair the commit I made in https://github.com/bids-standard/bids-validator/pull/1187/commits/fbd336005da37302b08675fd36e1ce7255e19d5b fixes the test issues ... so the problem is not with the code or data per se, but in the way the tests are triggered (npm run, etc.) ... now it fails with the codecov command (the step afterwards).

Not sure what needs fixing here.

2021-03-05 20:20 UTC, sappelhoff commented
>  so the problem is not with the code or data per se, but in the way the tests are triggered (npm run, etc.) ...

and the real issue was, that when trying to pass args to an "npm script", one needs to do it this way: `npm run <scriptname> -- --<arg1> --<arg2>` ... without the separating `--`, the args are silently passed to (and swallowed by) npm instead of to `<scriptname>`

the codecov job was probably an issue because it was not part of dev dependencies in the root package.json. but we'll see.

2021-03-05 21:11 UTC, sappelhoff commented
okay, I tried several things to make the githubPagesTest work ... I am giving up for now. The main issue is that the docker image used for that test was not NPM v7 ... so the last 4 commits can probably be reverted and replaced by an appropriate commit that results in npm v7 for that job.

2021-03-07 10:09 UTC, sappelhoff commented
one step further: githubPagesTest is now running, but breaking during the web-validator install:

> ModuleNotFoundError: Module not found: Error: Can't resolve 'pluralize' in '/root/project/bids-validator-web/components'

2021-03-08 12:53 UTC, sappelhoff commented
this is an absolute rabbit hole: Fix one issue, get the next one. :)

> 
> Build error occurred
Error: > Build failed because of webpack errors
    at /root/project/node_modules/next/dist/build/index.js:15:918
    at async /root/project/node_modules/next/dist/build/tracer.js:3:470

2021-03-08 13:17 UTC, sappelhoff commented
@happy5214, there was a test failure with hed-validator `3.0.5` that was resolved when downgrading to `3.0.4` (in https://github.com/bids-standard/bids-validator/pull/1187/commits/a395fd2e7de56a191682da34b997b5d2a4724b30). I only stumbled across this now, perhaps because my commit https://github.com/bids-standard/bids-validator/pull/1187/commits/d2d6a669490dfcd7f45f87adc5f4f89664e57b6a triggered the cache to be cleared.

Could you investigate, please?

2021-03-09 19:13 UTC, merged