PR to update bep009 according to newest PET-BIDS specification and the newest version of the validator
bids-standard/legacy-validator pull request #1204
Opened 2021-03-02 16:25 UTC by mnoergaard

This PR updates the validator to include large parts of the PET-BIDS specification, including schemas for PET and blood.

2021-03-08 12:35 UTC, sappelhoff commented
there are some conflicts @mnoergaard - can you solve them? Afterwards we could merge directly, as this is not going into `master` (yet)

2021-03-08 18:00 UTC, david-nishi requested changes

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet.json
> +  "allOf": [
These allOf fields can be condensed to a single array containing all four of the conditions.

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet.json
> +    "Manufacturer": { "type": "string", "minLength": 1 },
This is defined in common_definitions, which we can reference with
```
  "Manufacturer": { "$ref": "common_definitions.json#/definitions/Manufacturer" },
```

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet.json
> +    "ManufacturersModelName": { "type": "string", "minLength": 1 },
ManufacturersModelName is shared between pet, eeg, and meg, and is similar to a few other modalities. We could add this definition to common_definitions too (but it's not necessary).

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet.json
> +          "InjectedMass": {
With this constraint on InjectedMass and its unit, it would be better to move both fields from "dependencies" to "required". As it is now, an empty InjectedMass value would be allowed and would not trigger this condition expecting values of "n/a".

The same is true for SpecificRadioactivity and its unit.

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/bids_validator/rules/file_level_rules.json
> +    "regexp": "^[\\/\\\\](sub-[a-zA-Z0-9]+)[\\/\\\\](?:(ses-[a-zA-Z0-9]+)[\\/\\\\])?pet[\\/\\\\]\\1(_\\2)?(?:_trc-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_task-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?(?:_record
The regexs above don't appear to capture the sub, ses, or pet labels in the filenames, though they are tested for as parent directories. We believe the following regex (minus the recording piece for pet) should capture those:
```
^[\\/\\\\](sub-[a-zA-Z0-9]+)[\\/\\\\](?:(ses-[a-zA-Z0-9]+)[\\/\\\\])?pet[\\/\\\\](sub-[a-zA-Z0-9]+)(?:(_ses-[a-zA-Z0-9]+))?(?:_task-[a-zA-Z0-9]+)?(?:_trc-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?(?:_recording-[a-zA-Z0-9]+)?(@@@_pet_ext_@@@)$
```
For quick reference, here's the template from the spec:
```
sub-<label>/[ses-<label>/]
    pet/
    sub-<label>[_ses-<label>][_task-<label>][_trc-<label>][_rec-<label>][_run-<index>][_recording-<label>]_blood.tsv
    sub-<label>[_ses-<label>][_task-<label>][_trc-<label>][_rec-<label>][_run-<index>][_recording-<label>]_blood.json
    ```

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/bids_validator/tsv/non_custom_columns.json
> +  "blood": ["plasma_radioactivity", "wholeblood_radioactivity", "metabolite_parent_fraction"]
Not sure if it's the this or the spec that's most current, but the spec still lists "time" as a column. "time" is also present in [pet_example3](https://www.dropbox.com/sh/6egwsy442caribr/AABw6GrfvBQClbgie5Gaa6WLa?dl=0).

There are also two other (conditional) non-custom columns, "hplc_recovery_fractions" and "whole_blood_radioactivity".

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "WithdrawalRateUnit": { "type": "string" },
Looks like this should be "WithdrawalRate", type "number".

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "BloodDensity": { "type": "string", "minLength": 1 }
Another where either version could be valid, but the spec currently defines these two as numbers.

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "DispersionConstantUnits": { "type": "string" },
"TubingLengthUnits" and "DispersionConstantUnits" not in spec.

2021-03-08 18:00 UTC, david-nishi commented on bids-validator/validators/json/schemas/pet_blood.json
> +  "required": [
Appears to be missing "DispersionCorrected".

2021-03-08 18:08 UTC, david-nishi commented
@tranttommy and I compared it with the current specifications and came across a few discrepancies, though in some cases it could be the spec that needs updating.

2021-03-08 20:37 UTC, mnoergaard commented on bids-validator/bids_validator/rules/file_level_rules.json
> +    "regexp": "^[\\/\\\\](sub-[a-zA-Z0-9]+)[\\/\\\\](?:(ses-[a-zA-Z0-9]+)[\\/\\\\])?pet[\\/\\\\]\\1(_\\2)?(?:_trc-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_task-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?(?:_record
```suggestion
    "regexp": "^[\\/\\\\](sub-[a-zA-Z0-9]+)[\\/\\\\](?:(ses-[a-zA-Z0-9]+)[\\/\\\\])?pet[\\/\\\\](sub-[a-zA-Z0-9]+)(?:(_ses-[a-zA-Z0-9]+))?(?:_task-[a-zA-Z0-9]+)?(?:_trc-[a-zA-Z0-9]+)?(?:_rec-[a-zA-Z0-9]+)?(?:_run-[0-9]+)?(?:_recording-[a-zA-Z0-9]+)?(@@@_pet_ext_@@@)$",
```

2021-03-08 20:39 UTC, mnoergaard commented on bids-validator/bids_validator/tsv/non_custom_columns.json
> +  "blood": ["plasma_radioactivity", "wholeblood_radioactivity", "metabolite_parent_fraction"]
```suggestion
  "blood": ["time", "plasma_radioactivity", "whole_blood_radioactivity", "metabolite_parent_fraction", "hplc_recovery_fractions"]
```

2021-03-08 20:41 UTC, mnoergaard commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "WithdrawalRateUnit": { "type": "string" },
```suggestion
    "WithdrawalRate": { "type": "string" },

```

2021-03-08 20:42 UTC, mnoergaard commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "DispersionConstantUnits": { "type": "string" },
```suggestion

```

2021-03-08 20:43 UTC, mnoergaard commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "Haematocrit": { "type": "string", "minLength": 1 },
```suggestion
    "Haematocrit": { "type": "number" },

```

2021-03-08 20:44 UTC, mnoergaard commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "BloodDensity": { "type": "string", "minLength": 1 }
```suggestion
    "BloodDensity": { "type": "number" }

```

2021-03-08 20:45 UTC, mnoergaard commented on bids-validator/validators/json/schemas/pet_blood.json
> +    "WholeBloodAvail"
```suggestion
    "WholeBloodAvail",
    "DispersionCorrected"

```

2021-03-08 21:16 UTC, mnoergaard commented
> @tranttommy and I compared it with the current specifications and came across a few discrepancies, though in some cases it could be the spec that needs updating.

Excellent feedback - thanks a lot @david-nishi!

2021-03-09 00:50 UTC, david-nishi commented
Looks like there's one more minor change to be made, and then it should be good!
```
yarn lint
yarn run v1.22.0
$ ./node_modules/eslint/bin/eslint.js ./bids-validator/**/*.js

/root/project/bids-validator/utils/type.js
  289:5   error  Duplicate key 'isPET'          no-dupe-keys
  293:5   error  Duplicate key 'isPETBlood'     no-dupe-keys
  294:31  error  'petBloodData' is not defined  no-undef
```

2021-03-10 14:52 UTC, david-nishi approved these changes

2021-03-15 17:19 UTC, merged