Bep 009 tests
bids-standard/legacy-validator pull request #1229
Opened 2021-03-15 18:38 UTC by david-nishi

## Major Changes:
- Add integration tests for PET and PET blood containing datasets.
- Add unit tests for "pet" and "blood" file_level_rules.
- Updated "pet" and "blood" patterns in file_level_rules.

2021-03-15 19:28 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/anat/sub-01_ses-01_T1w.json
> +}
Just seeing this makes me remember: From the PET-BIDS specification, if pet data is available, we require the presence of "NonLinearGradientCorrection" in this file for the corresponding mr data. We still need to come up with a solution to this. 

The current dataset is an older version of the dataset in the pet bids-examples, and the gradient information is not included here.

2021-03-15 19:30 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/pet/sub-01_ses-01_pet.json
> +        "PlasmaAvail": false,
It seems that these examples are not fully updated according to the newest specification. This includes the blood information (should not be here), and the reconmatrixsize and imagevoxelsize. These will not cause any errors because they are currently not in the PET schema.

2021-03-15 19:35 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/pet/sub-01_ses-01_pet.json
> +        "PlasmaAvail": false,
Tried to fix this locally, but seems I am not allowed to make commits to this PR?

2021-03-15 19:43 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_3-pet_blood/sub-01/ses-01/pet/sub-01_ses-01_recording-manual_blood.json
> +  "PlasmaAvail": true,
Should we include an additional test where e.g. "PlasmaAvail": true, but then "plasma_radioactivity" is not included in the corresponding *.tsv file? This is what we would like to catch, as mentioned in our previous discussions on validating the tsv file.

2021-03-15 19:43 UTC, mnoergaard requested changes
Thanks for updating this, @david-nishi! I have a few comments and questions.

2021-03-18 16:07 UTC, david-nishi commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/anat/sub-01_ses-01_T1w.json
> +}
@ckrountree I think we'll want to make a ticket for implementing this.

2021-03-18 16:13 UTC, david-nishi commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/pet/sub-01_ses-01_pet.json
> +        "PlasmaAvail": false,
That's likely because I'm merging this from my fork. I think that for these specific test datasets, it'll be alright for now that they're not the newest specification because their purpose is to check for a specific error. The example datasets that we add to the [bids-examples](https://github.com/bids-standard/bids-examples) will need to be current. 

What would be the best way for us to obtain pet and pet_blood containing datasets that are up to the current spec?

2021-03-18 16:14 UTC, david-nishi commented on bids-validator/tests/data/broken_pet_example_3-pet_blood/sub-01/ses-01/pet/sub-01_ses-01_recording-manual_blood.json
> +  "PlasmaAvail": true,
Good idea. I've just push up commits that add that feature along with some tests for it.

2021-03-18 16:17 UTC, david-nishi commented
Thanks @mnoergaard! Implementation of validation across those specific JSON sidecar properties and their required tsv non-custom-columns (when set to true) has been added and will need further review.

2021-03-18 16:56 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/pet/sub-01_ses-01_pet.json
> +        "PlasmaAvail": false,
The examples here (https://github.com/bids-standard/bids-examples/tree/bep009_pet) should be up to the current spec!

2021-03-18 17:00 UTC, mnoergaard commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/anat/sub-01_ses-01_T1w.json
> +}
I think that sounds good! @melanieganz

2021-03-18 17:12 UTC, mnoergaard approved these changes
LGTM! Thanks @david-nishi!

2021-03-18 18:09 UTC, merged

2021-03-18 18:41 UTC, david-nishi commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/pet/sub-01_ses-01_pet.json
> +        "PlasmaAvail": false,
Awesome, thanks.

2021-03-22 14:15 UTC, melanieganz commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/anat/sub-01_ses-01_T1w.json
> +}
Yes, I agree, this is necessary as well. @david-nishi, please go ahead with making a ticket for implementing this.

2021-03-22 16:59 UTC, david-nishi commented on bids-validator/tests/data/broken_pet_example_2-pet_mri/sub-01/ses-01/anat/sub-01_ses-01_T1w.json
> +}
We’ll take a look into how this will fit into the current scope of work. Will keep you posted.