Migrate web site from Next to Vite
bids-standard/legacy-validator pull request #1430
Opened 2022-03-17 16:19 UTC by rwblair

Help match the openneuro build environment more closely.

I didn't need to use any of the workarounds in https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-app/vite.config.js to allow vite build to go off. Mosttly stayed with defaults from vite.

2022-03-17 16:44 UTC, nellh commented
> I didn't need to use any of the workarounds in https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-app/vite.config.js to allow vite build to go off. Mosttly stayed with defaults from vite.

I wonder if that's fixes in Vite or because they are dependencies of dependencies when used in OpenNeuro?

2022-03-17 16:45 UTC, rwblair commented
vite 2.8 vs vite 2.3.1 in openneuro, could be. The tsconfigs between ON and validator are slightly different so not sure if that affects it.

2022-03-17 16:49 UTC, effigies commented
Still breaking esbuild in Docker with the same errors...

2022-03-17 16:55 UTC, rwblair commented
I'm replicating those locally outside of docker, not sure whats up.

2022-03-17 17:18 UTC, rwblair commented
Right now the two packages throwing esbuild errors for me are nifti-js and jshint. nifti-js is from an unused require('assert') and jshint has the same import, but assert is being used.

nifti-js hasn't been updated since 2016 :(

2022-03-18 15:04 UTC, rwblair commented
To get the esbuild to work I cloned [nifti-js](https://github.com/rwblair/nifti-js) and removed the unused blocking import. Keeping it at my rwblair account is no good, should I push a copy to bids-standard, or should we be trying something like monkey patching? Project is effectively abandoned.

I also removed jshint from the config json parser. I have it return the json.parse error message instead, so this is considerably less verbose, not sure how much we care about this feature.

2022-03-18 15:24 UTC, effigies commented
Maybe try opening a PR against nifti-js before we fork?

Could we bundle it into our source tree (maybe as a submodule?) until it's merged and released upstream or we decide to officially fork?

2022-03-18 15:45 UTC, rwblair commented
scijs/nifti-js/pull/4

We'll see if it gets a response.

2022-03-18 15:54 UTC, nellh commented
[nifti-reader-js](https://github.com/rii-mango/NIFTI-Reader-JS) may be a good alternative, it's used by NiiVue so at least on the OpenNeuro side it could slightly reduce dependency weight.

2022-03-18 19:58 UTC, rwblair commented
nifti-header-js uses different names for header fields than the spec and nifti-js so that caused a bit of silliness (pixDims vs pixdim and dims vs dim). I should of just normalized the field names to match the spec in the parseHeader function, instead I changed them to match the libraries usage. Fun fact nifti-js was overwriting the dim array length property to match dim[0].

2022-03-22 18:24 UTC, nellh requested changes
Vite dev mode doesn't work without a build first and doesn't pick up changes (since it's executing the static build). I didn't find any issues with the production mode build.

```shell
-> npm run web-dev

> web-dev
> cd bids-validator-web && npm run dev


> bids-validator-web@0.0.0 dev
> vite

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "bids-validator". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "bids-validator". The package may have incorrect main/module/exports specified in its package.json.

    ../node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:

    ../node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:839:23)
    at Object.buildOrServe (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1133:7)
    at /home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:2074:17
    at new Promise (<anonymous>)
    at Object.build (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:2073:14)
    at Object.build (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1923:51)
    at /home/nell/Git/crn/bids-validator/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/components/App.jsx:6:21:
      6 │ import validate from 'bids-validator'
        ╵                      ~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
../node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "bids-validator". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "bids-validator". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1599:15)
    at /home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1245:28
    at runOnEndCallbacks (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1030:63)
    at buildResponseToResult (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1243:7)
    at /home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:1352:14
    at /home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:662:9
    at handleIncomingPacket (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/home/nell/Git/crn/bids-validator/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: bids-validator-web@0.0.0 
npm ERR!   at location: /home/nell/Git/crn/bids-validator/bids-validator-web 
```

2022-03-22 18:24 UTC, nellh commented on bids-validator/package.json
> -    "jshint": "^2.9.6",
jshint is also one of the largest deps, so I think this is worth dropping even if we lose a little functionality.

2022-03-22 19:05 UTC, rwblair commented
Unfortunately something like this won't work since it doesn't kill the old dev instance:
https://www.npmjs.com/package/npm-watch

Vites watch can't obviously kick off the validator rebuild as far as I can tell. Not sure about npm script interactions in that config:
https://vitejs.dev/config/#server-watch

2022-03-22 19:06 UTC, nellh commented on package.json
> +    "web-dev": "npm run build -w bids-validator && npm run dev -w bids-validator-web",
I don't think this is the right fix, since it dev mode still doesn't pick up new changes.

This change to bids-validator/package.json gets dev mode running but runs into some other issues.
```json
  "exports": {
    ".": {
      "import": "./index.js",
      "require": "./dist/commonjs/index.js"
    },
    "./cli": {
      "require": "./dist/commonjs/cli.js"
    },
    "./utils/consoleFormat": {
      "require": "./dist/commonjs/consoleFormat.js"
    }
  },
```

2022-03-25 18:58 UTC, rwblair commented
@nellh I couldn't figure out how to get it to go without using the openneuro shims, only needed two of them.

As best I can figure in the bids-validator esbuild was taking queues from the browser field in the package.json field, and there is no way to pass that information outside of packge.json to esbuild.

2022-03-25 20:10 UTC, rwblair commented
rwblair/bids-validator#3
An alternative idea that goes back to using dist/esm/index.js, and enabling esbuild's built in watch functionality on run web-dev, and then having the esbuild and vite dev run simultaneously using a package called concurrently.

2023-06-30 16:55 UTC, closed without merging