[WIP] Add summary generation to schema-prototype
bids-standard/legacy-validator pull request #1481
Opened 2022-06-29 20:33 UTC by rwblair

Summary generated is an object literal being exported in src/summary/summary. May be better served as a class. file counts, modalities, and participant metadata seem to be working. Task name is reliant on parsing json files. Right now summaryUpdate code is trying to access the json field in the current context to see if they have a TaskName field.

Also have a some `error: AssertionError: Test case is leaking async ops.` to figure out.

2022-06-29 21:16 UTC, nellh commented on bids-validator/src/summary/summary.ts
> +    const fileBuffer = await readAll(denoReader)
The file object should probably just have a method for this, like .text() (fetch style). Otherwise we're going to do this all over the place. I like that this reads the stream though, portable to the browser!

2022-06-29 21:16 UTC, nellh commented on bids-validator/src/validators/bids.ts
> +    updateSummary(context)
To fix the async issue, looks like you just need to await this.

2022-07-01 14:45 UTC, rwblair commented on bids-validator/src/tests/local/common.ts
> +    summary: formatSummary(summary),
This seems silly. should just make summary a class, look more like issues.

2022-07-01 16:35 UTC, rwblair commented on bids-validator/src/files/deno.ts
> +    if (dirEntry.isFile || dirEntry.isSymlink) {
Running locally on an annexed dataset I had to add this to see any files. What kinds of problems could having this cause?

2022-07-01 16:44 UTC, rwblair commented
@nellh  Testing on ds000003 the deno summary matches current summary with the exception of size and datatypes. Current validator will attempt to use filename suffix as a datatype in some cases. For ds003 this means `inplaneT2` and `events` gets listed as a datatype. Can you think of anywhere that would rely on `events` being in the datatypes?

Deno correctly calculates the size where as current valdiator outputs 0. May have something to do with this: https://github.com/bids-standard/bids-validator/pull/1481/files#r912104701

Anything I should add or update?

2022-07-01 17:52 UTC, nellh commented
> @nellh Testing on ds000003 the deno summary matches current summary with the exception of size and datatypes. Current validator will attempt to use filename suffix as a datatype in some cases. For ds003 this means `inplaneT2` and `events` gets listed as a datatype. Can you think of anywhere that would rely on `events` being in the datatypes?

At least on the OpenNeuro side, nothing depends on events being listed and I think we should stick to the more spec accurate output here.

2022-07-01 17:52 UTC, nellh requested changes

2022-07-01 17:52 UTC, nellh commented on bids-validator/src/files/deno.ts
> +  const ignore = new FileIgnoreRulesDeno(['.git**'])
We could make this the default value for FileIgnoreRulesDeno so that other instantiations (tests, etc) also use this default.

2022-07-01 17:52 UTC, nellh commented on bids-validator/src/summary/summary.ts
> +      let tsvContents = await context.file.text()
```suggestion
      const tsvContents = await context.file.text()
```

2022-07-01 17:52 UTC, nellh commented on bids-validator/src/summary/summary.ts
> +export const summary = new Summary()
I think it would be better to just export the class and construct it in validate() like the Issues class.

2022-07-08 17:18 UTC, nellh approved these changes

2022-07-08 17:27 UTC, merged