Schema/expression language
bids-standard/legacy-validator pull request #1535
Opened 2022-09-23 18:00 UTC by rwblair

- Introduces functions for schema expression language outlined [here](https://github.com/bids-standard/bids-specification/tree/master/src/schema#Expressions).
- Adds nifti header loading but should revised. Causes a considerable slow down from loading whole nifti files synchronously.
- Adds fully loading events.tsv for associations checks.

2022-09-23 18:14 UTC, rwblair commented
Need to add tests. Expression testing examples could come from specification itself a la bids-standard/bids-specification#1274

2022-09-23 19:01 UTC, nellh requested changes

2022-09-23 19:01 UTC, nellh commented on bids-validator/src/files/nifti.ts
> +export function loadHeader(file: BIDSFile) {
```suggestion
export function loadHeader(file: BIDSFileDeno) {
```

2022-09-23 19:01 UTC, nellh commented on bids-validator/src/files/nifti.ts
> +  const header = nifti.readHeader(Deno.readFileSync(file._getPath()).buffer)
```suggestion
  const buf = file.readBytes(1024)
  const header = globalThis.nifti.readHeader(buf.buffer)
```

Added this in #1536 to keep this from requiring the private path method.

2022-09-23 19:01 UTC, nellh commented on bids-validator/src/schema/context.ts
> +    await Promise.all([
```suggestion
    await Promise.allSettled([
```

2022-10-10 16:15 UTC, nellh approved these changes

2022-10-12 15:46 UTC, merged