DOC: Add usage instructions for running from deno.land
bids-standard/legacy-validator pull request #1770
Opened 2023-08-04 18:00 UTC by effigies

The current README is overly developer-focused. This adds docs that will appear on the deno.land landing page (https://deno.land/x/bids_validator) that tell users how to use what's there.

2023-08-05 18:45 UTC, sappelhoff approved these changes
thanks!

2023-08-24 17:16 UTC, nellh requested changes
Looks good except we should update the --legacy option docs since it was removed.

2023-08-24 17:16 UTC, nellh commented on bids-validator/src/README.md
> +By default only schema derived validation rules are run. The legacy validator can be run at the same time with `--legacy` and this may improve coverage for issues not yet implemented in the schema va
This is stale, the legacy option no longer works and we should remove the references to it.
```suggestion
```

2023-08-24 17:31 UTC, nellh approved these changes

2023-08-24 17:32 UTC, merged