issue-256
bids-standard/legacy-validator pull request #257
Opened 2017-02-16 18:44 UTC by suyashdb

added warning for participants with age 89 or 89+

2017-02-17 19:01 UTC, chrisgorgo requested changes
Please add a test.

2017-02-17 19:01 UTC, chrisfilo commented on utils/issues/list.js
> +        key: 'Participants age 89 or 89+',
"89 or higher"

2017-02-17 19:01 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'Participants age is 89 or 89+. Tag them as 89+'
Give more explanation about why this should be changed (privacy concerns). Link to some more information for example: https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/

2017-02-17 19:01 UTC, chrisfilo commented on validators/tsv.js
> +        var ageIdColumn = headers.indexOf("age\r");
Isn't this the same as `ageIndex` as defined in line 147?

2017-02-17 19:01 UTC, chrisfilo commented on validators/tsv.js
> +        if (age == 89 || age > 89) {
Isn't his the same as `age >= 89`?

2017-02-17 19:01 UTC, chrisfilo commented on validators/tsv.js
> +            age_89_plus = true;
This variable is not used anywhere.

2017-02-17 19:01 UTC, chrisfilo commented on validators/tsv.js
> +        if (age == 89 || age > 89) {
Als don't you need to cast this to float to do this comparison?

2017-02-17 19:01 UTC, chrisfilo commented on validators/tsv.js
> +        var row = row.slice(0,-1)
Why is this necessary?

2017-02-19 22:31 UTC, suyashdb commented on validators/tsv.js
> +        var row = row.slice(0,-1)
as every row in tsv file ends with /r, sliced last two characters of every rows. 
For eg:  sub-01    group-A    20/r

2017-02-20 00:27 UTC, chrisfilo commented
Are you sure the end of the line characters are included? If so we need
take care of files created with UNIX systems (new line characters) and
windows (new line and carriage return characters). It might be better to
deal with this when you cast from string to a number.

On Feb 19, 2017 2:31 PM, "Suyash" <notifications@github.com> wrote:

> *@suyashdb* commented on this pull request.
> ------------------------------
>
> In validators/tsv.js
> <https://github.com/INCF/bids-validator/pull/257#discussion_r101930815>:
>
> > @@ -142,6 +142,28 @@ module.exports = function TSV (file, contents, fileList, callback) {
>          }
>
>      }
> +  // check partcipants.tsv for age 89+
> +    var headers = rows[0].split('\t');
> +    var ageIndex = headers.indexOf('age');
> +    if (file.name === 'participants.tsv'){
> +      for (var i = 0; i < rows.length; i++) {
> +        var row = rows[i];
> +        var row = row.slice(0,-1)
>
> as every row in tsv file ends with /r, sliced last two characters of every
> rows.
> For eg: sub-01 group-A 20/r
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/INCF/bids-validator/pull/257#discussion_r101930815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOkp1oCOFtrdd3qyuMtgugGC9JPU94vks5reMKwgaJpZM4MDZN7>
> .
>

2017-02-20 05:10 UTC, suyashdb commented
It was the case for the test dataset(ds212) participant file, i have been
using. Let me check other tsv files too.



On Sun, Feb 19, 2017 at 4:27 PM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com) Add cleanup rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DYmnt%252BjWbnp4K6g8O2lbZSh7we9Hx1yHyHVMlq8qp%252BWk%253D%26token%3DrT2bMBR6hzRB%252Fw%252F56qCFOJYVKjqs5f51xAI9Mjae1zZdZJyaF7%252Fo%252BGtpXEq%252FrnVYjG0Cshg2Vbg22OxCAeoxRXnSUzNeJW0WTfG2auPVhSKfTA8gjUj7wPooq6PNGRrTHIQnQXhklTAtoupQxgKo6Q%253D%253D&tc_serial=28965056906&tc_rand=690647944&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=28965056906&tc_rand=690647944&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>
> Are you sure the end of the line characters are included? If so we need
> take care of files created with UNIX systems (new line characters) and
> windows (new line and carriage return characters). It might be better to
> deal with this when you cast from string to a number.
>
> On Feb 19, 2017 2:31 PM, "Suyash" <notifications@github.com> wrote:
>
> > *@suyashdb* commented on this pull request.
> > ------------------------------
> >
> > In validators/tsv.js
> > <https://github.com/INCF/bids-validator/pull/257#discussion_r101930815>:
> >
> > > @@ -142,6 +142,28 @@ module.exports = function TSV (file, contents,
> fileList, callback) {
> > }
> >
> > }
> > + // check partcipants.tsv for age 89+
> > + var headers = rows[0].split('\t');
> > + var ageIndex = headers.indexOf('age');
> > + if (file.name === 'participants.tsv'){
> > + for (var i = 0; i < rows.length; i++) {
> > + var row = rows[i];
> > + var row = row.slice(0,-1)
> >
> > as every row in tsv file ends with /r, sliced last two characters of
> every
> > rows.
> > For eg: sub-01 group-A 20/r
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/INCF/bids-validator/pull/257#discussion_r101930815>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/
> AAOkp1oCOFtrdd3qyuMtgugGC9JPU94vks5reMKwgaJpZM4MDZN7>
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/INCF/bids-validator/pull/257#issuecomment-280962515>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKotn_Zda728lZBazM5o9XFuPFCMhvyoks5reN4HgaJpZM4MDZN7>
> .
>
>

2017-02-21 01:44 UTC, suyashdb commented
When i checked other tsv files, i observed that not all tsv files had EOL characters. Hence, first tried to deal with EOL characters while casting from string to Numbers. However, in case of header row, because in some files there was age\r or age\n and in others just age, i had to trim these EOL char while reading rows itself. 

For this reason, i went with the above logic (as per latest commit). 
Please let me know if you foresee any limitation in using this logic.

```
var header = rows[0].replace(/(\r\n|\n|\r)/gm,"").split('\t'); //remove EOL character if any
var ageIdColumn = header.indexOf("age");
```

I will add test in another commit.

2017-02-21 01:47 UTC, chrisfilo commented
This might be helpful https://www.w3schools.com/jsref/jsref_trim_string.asp

On Mon, Feb 20, 2017 at 5:44 PM, Suyash <notifications@github.com> wrote:

> When i checked other tsv files, i observed that not all tsv files had EOL
> characters. Hence, first tried to deal with EOL characters while casting
> from string to Numbers. However, in case of header row, because in some
> files there was age\r or age\n and in others just age, i had to trim these
> EOL char while reading rows itself.
>
> For this reason, i went with the above logic (as per latest commit).
> Please let me know if you foresee any limitation in using this logic.
>
> var header = rows[0].replace(/(\r\n|\n|\r)/gm,"").split('\t'); //remove EOL character if any
> var ageIdColumn = header.indexOf("age");
>
> I will add test in another commit.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/INCF/bids-validator/pull/257#issuecomment-281221898>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOkp6ceSXVHgo4L8tUOF4Y-moWv37Srks5rekFlgaJpZM4MDZN7>
> .
>

2017-03-07 20:52 UTC, merged