Illegal character underscore in taskname and Acq name
bids-standard/legacy-validator pull request #283
Opened 2017-05-26 00:45 UTC by suyashdb

Closes #221

2017-06-12 17:20 UTC, chrisfilo commented
Is this ready for review? Would it be hard to expand to `sub-` and `ses-` (I just run into another dataset that made such mistake).

2017-06-12 17:47 UTC, suyashdb commented
I haven't been able to write correct tests for this PR yet. Is it ok to merge for now without tests?  

Can i create another PR for finding illegal character in sub-/ses-? I think it should be not difficult as finding illegal character in taskname and acq.

2017-06-12 17:49 UTC, chrisfilo commented
Let's wait for tests until we merge this one and do sub-/ses- in another PR.

On Mon, Jun 12, 2017 at 10:47 AM, Suyash <notifications@github.com> wrote:

> I haven't been able to write correct tests for this PR yet. Is it ok to
> merge for now without tests?
>
> Can i create another PR for finding illegal character in sub-/ses-? I
> think it should be not difficult as finding illegal character in taskname
> and acq.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/INCF/bids-validator/pull/283#issuecomment-307864647>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOkpwNFvHwMpquoRhWkW-oJGtdxBKIqks5sDXmugaJpZM4NnDSi>
> .
>

2017-06-15 22:05 UTC, chrisfilo commented
Try following the pattern of this test: https://github.com/suyashdb/bids-validator/blob/4632dabfa7616dc58398af92915239f4bd820d7f/tests/bids.spec.js#L83

2017-07-27 21:28 UTC, suyashdb commented
@chrisfilo Ready for review and merge

2017-08-02 18:07 UTC, chrisgorgo requested changes

2017-08-02 18:07 UTC, chrisfilo commented on utils/issues/list.js
> +        key: 'Task Name contain illegal Character -/_',
let's keep keys as all caps one string (but with underscores)

2017-08-02 18:07 UTC, chrisfilo commented on tests/bids.spec.js
> +            assert(errors[0].code === '55' && errors[1].code === '57');
let's limit this to one error (57)

2017-08-02 18:07 UTC, chrisfilo commented on validators/bids.js
> +
Could you rewrite this so it would be easier to add this check for new keys in the future.

2017-08-03 21:39 UTC, suyashdb commented
@chrisfilo can you please review and merge?

2017-08-03 22:51 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'Task Name contain an Illegal Character hypen or underscore. Please edit the filename as per BIDS spec.'
Why are you changing the name and meaning of this error instead of adding a new one?

2017-08-03 22:51 UTC, chrisfilo commented on validators/bids.js
> +        var taskre = /sub-(.*?)_task-[a-zA-Z0-9]*[_-][a-zA-Z0-9]*(?:_acq-[a-zA-Z0-9-]*)?(?:_run-\d+)?_/g;
`task_re` for consistency

2017-08-03 22:51 UTC, chrisfilo commented on validators/bids.js
> +            var res = taskre.exec(completename);
`task_res` for consistency

2017-08-03 22:54 UTC, chrisfilo commented on validators/bids.js
> +            if (acq_res){
why not `!==` here as well? is there a difference?

2017-08-03 22:55 UTC, chrisfilo commented on validators/bids.js
> +            }
This is better than previous iteration, but you could make the code even more compact if you define a list (or dictionary) of triplets: regular expression, error code, evidence text prefix; and iterate over them.

2017-08-04 21:43 UTC, suyashdb commented on utils/issues/list.js
> +        reason: 'Task Name contain an Illegal Character hypen or underscore. Please edit the filename as per BIDS spec.'
That was not intended. my branch was not up to date with master. Will get this fixed.

2017-08-04 21:43 UTC, suyashdb commented on validators/bids.js
> +            if (acq_res){
its same, I will correct.

2017-08-09 18:01 UTC, merged