Checks if Sub and Ses ID in path and filename mismatch
bids-standard/legacy-validator pull request #313
Opened 2017-09-24 01:46 UTC by suyashdb

closes #264.

2017-09-29 13:26 UTC, chrisfilo commented
Please resolve conflicts.

2017-09-29 13:28 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'sub-id in the filename doesn\'t match with the path of the file. File seems to be saved in incorrect subject directory.'
let's be consistent and call this sesssion label not `ses-id`

2017-09-29 13:28 UTC, chrisfilo commented on utils/issues/list.js
> +        severity: 'warning',
Why is this just a warning?

2017-09-29 13:29 UTC, chrisfilo commented on utils/issues/list.js
> +    63: {
Is this used anywhere?

2017-10-02 22:23 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'subject label in the filename doesn\'t match with the path of the file. File seems to be saved in incorrect subject directory.'
capital "S" in "Subject"

2017-10-02 22:25 UTC, chrisfilo commented on utils/issues/list.js
> -        key: 'SUBJECT_VALUE_CONTAINS_ILLEGAL_CHARECTER',
Why are you modifying those errors instead of creating new ones?  Weren't the old ones already used?

2017-10-04 21:28 UTC, suyashdb commented
Ready for review.

2017-10-09 22:43 UTC, chrisgorgo commented on validators/bids.js
> +                        code: 61,
Not 64?

2017-10-09 22:43 UTC, chrisgorgo commented on validators/bids.js
> +                        code: 62,
Not 65?

2017-10-09 22:43 UTC, chrisgorgo commented on tests/type.spec.js
> +                if (issues[i]['code'] === 62) {
not 64?

2017-10-09 22:43 UTC, chrisgorgo commented on tests/type.spec.js
> +                else if (issues[i]['code'] === 63) {
not 65?

2017-10-13 06:05 UTC, chrisgorgo requested changes
couple of small things, almost there!

2017-10-13 06:05 UTC, chrisfilo commented on tests/type.spec.js
> +    // var issues = [{code: 61}, {code: 62}];
why is this commented out? can we remove this?

2017-10-13 06:05 UTC, chrisfilo commented on tests/type.spec.js
> +    var code63_seen = false;
the names of those variables do not correspond to the issue numbers anymore - this is confusing

2017-10-18 18:03 UTC, merged