Do not check files in derivatives for illegal characters in sub,ses, task,acq name
bids-standard/legacy-validator pull request #318
Opened 2017-09-28 21:21 UTC by suyashdb

Closes #317

2017-09-29 13:24 UTC, chrisgorgo requested changes

2017-09-29 13:24 UTC, chrisfilo commented on validators/bids.js
> +            if(!completename.startsWith('/derivatives')) {
We should include `/code` and `/sourcedata` here as well.

2017-09-29 16:57 UTC, suyashdb reviewed
I have added /code and /sourcedata to the check

2017-10-02 22:22 UTC, chrisgorgo approved these changes

2017-10-02 22:22 UTC, merged