Validate slice timing array with RepetitionTime
bids-standard/legacy-validator pull request #352
Opened 2017-10-27 21:51 UTC by suyashdb

Closes #302.

2017-10-27 21:56 UTC, suyashdb commented
@chrisfilo: Ready for review.

2017-10-27 22:15 UTC, chrisgorgo requested changes

2017-10-27 22:15 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'SliceTiming value/s in json contains invalid value as it is greator than RepetitionTime.'
Put the names of the fields in quotes (consistent with other error descriptions) and don't mention the JSON file.

2017-10-27 22:15 UTC, chrisfilo commented on tests/json.spec.js
> +	it('sidecar SliceTiming shouldnot be greator than RepetitionTime', function(){
should not

2017-10-27 22:15 UTC, chrisfilo commented on tests/json.spec.js
> +			assert(issues.length === 1 && issues);
Please verify that the expected error was raised (via the error code) - not just any issue.

2017-10-27 22:15 UTC, chrisfilo commented on validators/json.js
> +    if (sidecar.hasOwnProperty('RepetitionTime') && sidecar.hasOwnProperty('SliceTiming')) {
This needs to be done on the level of merged dictionary not individual JSON file. RepetitionTime and SliceTiming could be defined in different files.

2017-10-27 22:15 UTC, chrisfilo commented on validators/json.js
> +        });
Why not do a for loop that goes over all values in SliceTiming and checks each against RepetitionTime. The look could break at the first incorrect value.

2017-10-27 22:15 UTC, chrisfilo commented on utils/issues/list.js
> +        reason: 'SliceTiming value/s in json contains invalid value as it is greator than RepetitionTime.'
The error should also mention that SliceTiming values should be in seconds not milliseconds (common mistake).

2017-10-30 18:32 UTC, chrisgorgo reviewed
Thanks! Much better!
Code climat seems to be unhappy about nested ifs https://codeclimate.com/github/INCF/bids-validator/pull/352#issues. Here are some tips how to improve this. https://en.wikibooks.org/wiki/Computer_Programming/Coding_Style/Minimize_nesting

2017-10-30 18:32 UTC, chrisfilo commented on tests/nii.spec.js
> +            assert(issues[2].code === 66);
could you also add assertions for number of errors and warnings?

2017-10-30 18:36 UTC, suyashdb commented on tests/nii.spec.js
> +            assert(issues[2].code === 66);
Sure will do. 
Yes i am trying to resolve the code climate errors. :)

2017-10-30 19:29 UTC, suyashdb commented
@chrisfilo 
CircelCi and Code Climate both looks happy this time!

2017-10-30 19:32 UTC, chrisgorgo approved these changes

2017-10-30 19:32 UTC, merged