No bids specific nifti files in the dataset
bids-standard/legacy-validator pull request #372
Opened 2017-12-05 19:57 UTC by suyashdb

Closes #325

2017-12-05 21:24 UTC, chrisfilo commented on validators/bids.js
> +                nifti_fileList.push(file.relativePath);
@suyashdb : "This has to be removed"

2017-12-05 21:25 UTC, chrisfilo commented on validators/bids.js
> +                nifti_fileList.push(file.relativePath);
Why is this added again?

2017-12-05 21:31 UTC, chrisfilo commented
Please iterate over subjects and give error for every subject that doesn't have any BIDS specific files.

2017-12-05 21:32 UTC, chrisgorgo requested changes

2017-12-05 21:32 UTC, chrisfilo commented on validators/bids.js
> +            if (file.name.endsWith('.nii') || file.name.endsWith('.nii.gz')) {
please don't restrict this test to niftis

2017-12-08 17:22 UTC, chrisfilo commented
There was another dataset like this in OpenNeuro. What is the ETA on this PR?

2017-12-08 17:54 UTC, chrisfilo commented
I just realized that this test could be achieved by comparing `summary.subjects` count with number of `sub-*` subfolders. Should be very easy to implement.

2017-12-08 18:32 UTC, suyashdb commented
I am aiming to submit it my today evening..

2017-12-09 01:31 UTC, suyashdb commented
@chrisfilo:
I tried reducing the codeclimate complexity from 15 to 6. Not sure how can i reduce to 5 to pass codeclimate threshold. :)

CircleCI: as per my initial digging, linter is giving error for ES6 syntax. Trying on different linter if that works.

2017-12-10 03:15 UTC, chrisfilo commented
https://github.com/ternjs/acorn/issues/500

2017-12-13 03:19 UTC, closed without merging