Issue 275
bids-standard/legacy-validator pull request #418
Opened 2018-02-27 19:39 UTC by SetCodesToFire

Solving  #275

2018-02-27 19:45 UTC, SetCodesToFire commented
Hi @chrisfilo  ,
Codeclimate's check need to be resolved for this PR

2018-02-28 04:46 UTC, chrisgorgo requested changes

2018-02-28 04:46 UTC, chrisfilo commented on tests/tsv.spec.js
> +
Could you add a test where filename column is present and there are no errors?

2018-02-28 04:49 UTC, SetCodesToFire commented on tests/tsv.spec.js
> +
okay sure.

2018-02-28 05:05 UTC, chrisfilo commented
Awesome! Thanks!

2018-02-28 05:05 UTC, merged