schema checks are made against merged json dictionaries
bids-standard/legacy-validator pull request #514
Opened 2018-08-20 22:43 UTC by olgn

fixes #438 

* separates json file reading from json validation - this allows all the json data to be present when validating a single json file 
* json schema validation is now runs against the mergedDictionary generated from all sidecars that are related to the file
* existing json tests were updated to reflect this new change
* new unit tests implemented to ensure that a) schemas are validated against merged dictionaries and b) local values of a field are preferred to inherited values (value furthest from the root is used for schema validation)

2018-08-23 20:12 UTC, olgn commented
@chrisfilo would you like for me to refactor this pr for the issue referenced above (#477)?

2018-08-23 23:08 UTC, chrisfilo commented
I think it's worth investigating. I suspect #477 is specific to MEG and TSV files.

2018-08-28 19:35 UTC, nellh requested changes
Just one question, otherwise I think this looks good.

2018-08-28 19:35 UTC, nellh commented on utils/files.js
> +          resolve(null, e.target.result)
This looks odd to me. I think the null return is meant to indicate a failure, so it should not resolve. Is there a reason it's like this?

2018-08-28 19:35 UTC, nellh commented on validators/bids.js
> +              return
This return has no effect.

2018-08-29 21:10 UTC, nellh approved these changes

2018-08-29 21:11 UTC, merged

2018-08-31 18:14 UTC, jasmainak commented
Thanks! This is really useful