[FIX #575] readDir.js now follow Symlink directories
bids-standard/legacy-validator pull request #579
Opened 2018-09-21 20:14 UTC by naveau

Should fix #575 

I don't have any test for this PR. Mocking symlink (https://github.com/tschaub/mock-fs) is probably an overkill.

2018-09-25 17:54 UTC, olgn requested changes
@naveau this looks great. 

I have requested one small change for performance reasons

2018-09-25 17:54 UTC, olgn commented on utils/files/readDir.js
> +  var isDir = fs.lstatSync(path).isDirectory()
can we set fs.lstatSync(path) to a variable and then reuse it on this line (125) and this line (126)? for performance reasons it makes sense to only call this function once.

2018-09-26 12:50 UTC, naveau commented on utils/files/readDir.js
> +  var isDir = fs.lstatSync(path).isDirectory()
Done. Sounds indeed reasonable !

2018-09-26 18:10 UTC, olgn approved these changes

2018-09-26 18:11 UTC, merged