updating ieeg spec with new info
bids-standard/legacy-validator pull request #591
Opened 2018-09-26 22:18 UTC by choldgraf

this PR updates the validator with changes in the ieeg spec since the latest push.

cc @dorahermes

2018-09-29 01:33 UTC, jasmainak commented on validators/schemas/ieeg.json
> +                },
no tests to update for this?

2018-10-22 18:50 UTC, sappelhoff requested changes
Please also address renaming `.dat` to `.eeg` in the regexps:

https://github.com/bids-standard/bids-validator/blob/3876694533738f2df73de14e9745a4f5f4ba3304/validators/bids/groupFileTypes.js#L53-L67

https://github.com/bids-standard/bids-validator/blob/cbcb0d31c5a945ef8be9e5c2b4e380b6d7a01a58/bids_validator/rules/file_level_rules.json#L179

... and perhaps in other spots. BrainVision has its binary data in `.eeg` files, nobody can remember where the `.dat` came from

2018-10-30 14:41 UTC, choldgraf commented
I'm working on implementing these changes, but it seems that the validator codebase has changed a bit since I last took a pass. A few questions:

1. @chrisfilo is there a place that describes the current organization of the codebase from a developer standpoint?
2. As @sappelhoff notes above, what's the difference between the file names specified in `groupFileTypes.js` vs. those in `file_level_rules.json`? Should they just be the same?
3. Where should something like "warn if the data is a subset of extensions" go?
4. Does anybody know if BIDS has a policy for what to do if a required field is missing? (e.g. we have hardwarefilters as required, but sometimes people simply don't have it)

2018-10-30 18:36 UTC, chrisfilo commented
1. Unfortunately there isn't, but if you have specific questions perhaps @olgn can help
2. Not sure what that list is doing in `groupFileTypes.js` It probably shouldn't be there.
3. Hmm... I don't quite follow. What is a "subset of extension?
4. If a required field is missing this should be an error. Perhaps this field should be recommended.

2018-10-30 21:59 UTC, choldgraf commented
@chrisfilo I mean that when we check for data extensions (eg, EDF, fif, etc) a subset of those extensions are allowed, but not "officially recommended". We want to raise a warning if those are found, but still allow them to pass the validator.

2018-10-31 23:35 UTC, choldgraf commented
I believe that @olgn was the one that added the files in `groupFileTypes.js`...perhaps they can clarify what this section does?

2018-11-01 00:13 UTC, choldgraf commented
ok - I think that most of the changes are implemented that were in the google doc. Only a couple questions remain:

1. Not sure where (or if) we can raise a warning if a subset of extensions is used for data.
2. Not sure what's up with the `groupFileTypes.js` code (see comment above)

Other than that, I need to make sure that tests pass on the validator (can't do this now because I'm on a plane w/ crappy internet).

2018-11-01 08:01 UTC, sappelhoff requested changes
Looks good, I think the tests were failing because you edited the header columns in the `chanels.tsv` files, but forgot to also truncate the other columns. Other than that, the main suggestions are:

1. remove the required `reference`  column, it is only recommended in the spec
2. please change the `.dat` extensions to `.eeg` in the regexp sections for iEEG
3. potentially remove these unknown extensions tdix, tmet, ... - see [here](https://github.com/bids-standard/bids-validator/issues/510#issuecomment-431556824)

Finally, we also wanted to add the `value` and `sample` fields for the `events.tsv`. I got started with this for EEG already (see https://github.com/bids-standard/bids-validator/pull/599), but @chrisfilo wants it to be conditional on the bep flag, so we might want to wait with that in order not to complicate things.

I made some inline code suggestions that should be quick fixes :-)

2018-11-01 08:01 UTC, sappelhoff commented on validators/tsv/tsv.js
> +    checkheader('reference', 5, file, 72)
According to the [spec](https://docs.google.com/document/d/1qMUkoaXzRMlJuOcfTYNr3fTsrl4SewWjffjMD5Ew6GY/edit#heading=h.vntcs5d7jpb3), the reference column is recommended, not required ... I think this is with good reason, because it would only be of relevance in a bipolar recording scheme or with many special AUX channels that all have their own special reference. I suggest to remove this from the check:

```suggestion

```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
> +      'name\ttype\tunits\textra-column\thigh_cutoff\treference\n' +
fix according to removing `reference` as a required field (see below)
```suggestion
      'name\ttype\tunits\textra-column\thigh_cutoff\n' +
```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
>        'value-one\tvalue-two\tvalue-three\tvalue-four\tvalue-five\tvalue-six\tvalue-seven\tvalue-eight'
too many columns in this row
```suggestion
      'value-name\tvalue-type\tvalue-units\tvalue-fake\tvalue-highcut'
```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
> +      'name\ttype\tunits\tlow_cutoff\textra-column\treference\n' +
again, remove reference (see below)
```suggestion
      'name\ttype\tunits\tlow_cutoff\textra-column\n' +
```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
>        'value-one\tvalue-two\tvalue-three\tvalue-four\tvalue-five\tvalue-six\tvalue-seven\tvalue-eight'
and too many values (same as above)
```suggestion
      'value-name\tvalue-type\tvalue-units\tvalue-lowcut\tvalue-fake'
```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
>    it('should not allow iEEG channels.tsv files without reference column', function() {
this test should be deleted, because the reference column is not required (needs to be changed below as well) ... I'd love to make a suggestion here as well, but Github does not allow multi-line suggestions so far :-O

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
> +      'name\ttype\tunits\tlow_cutoff\thigh_cutoff\treference\n' +
```suggestion
      'name\ttype\tunits\tlow_cutoff\thigh_cutoff\n' +
```

2018-11-01 08:01 UTC, sappelhoff commented on tests/tsv.spec.js
> +      'value-one\tvalue-two\tvalue-three\tvalue-four\tvalue-five\tvalue-six\t'
```suggestion
      'value-name\tvalue-type\tvalue-units\tvalue-lowcut\tvalue-highcut'
```

2018-11-06 21:25 UTC, sappelhoff commented on validators/json/schemas/ieeg.json
>      "iEEGReference"
@choldgraf I think the error is related to these lines:

https://github.com/bids-standard/bids-validator/blob/551878e7dfb6af1e641676521d2066056192e41c/tests/json.spec.js#L108-L115

You need to update the test to reflect the new "required" key/value pairs that have changed here (see lines 51 to 55 right above this comment)

2018-11-06 21:27 UTC, sappelhoff approved these changes
+1 for merge after the remaining fix of the test:

https://github.com/bids-standard/bids-validator/blob/551878e7dfb6af1e641676521d2066056192e41c/tests/json.spec.js#L108-L115

2018-11-06 23:47 UTC, choldgraf commented
Hmm, I tried updating those fields in the test, and I'm still getting an error on that one. It seems like the required fields are all accounted for in the test:

required fields:

https://github.com/bids-standard/bids-validator/pull/591/files#diff-565f0182ad77f553142b7ff49357cd13R51

tested fields:

https://github.com/bids-standard/bids-validator/pull/591/files#diff-bacd38195c17182690f432a3e896cf20R109

Any idea what's going on?

2018-11-07 06:44 UTC, sappelhoff commented on tests/json.spec.js
> +      SoftwareFilters: 'high-pass',
@choldgraf I think the way the software filter is specified does not conform to what we require:
```json
    "SoftwareFilters": {
      "anyOf": [
        {"type": "object", "additionalProperties": {"type":"object"}},
        {"type": "string", "pattern": "^n/a$"}
      ]
    }
```

It should either be: a string `"na"`

... or it could be an object of objects: `{'HighPass': {'HalfAmplitudeCutOffHz': 1, 'RollOff: '6dB/Octave'}}`

```suggestion
      SoftwareFilters: {'HighPass': {'HalfAmplitudeCutOffHz': 1, 'RollOff: '6dB/Octave'}},
```

2018-11-07 19:45 UTC, choldgraf commented
can anybody suggest a way to launch an interactive debugger during an `npm` test? It's super frustrating that I can't figure out what exactly the error is in the JSON dictionary...there's gotta be a more efficient way to do this than me looking at the circle builds each time...

2018-11-08 10:19 UTC, sappelhoff commented
not a real answer to your problem, but instead of `npm test`, you can also run these other commands that are being run by CircleCI:

https://github.com/bids-standard/bids-validator/blob/aa58a07258f398673cea98c041cd028f2a18b3fd/circle.yml#L17-L28

Then at least you don't have to wait for Circle to build something 🤔

2018-11-08 15:29 UTC, chrisfilo commented
WebStorm is a convenient way to debug tests. Works like any other ide
pretty similar to pycharm.

On Thu, Nov 8, 2018, 2:19 AM Stefan Appelhoff <notifications@github.com
wrote:

> not a real answer to your problem, but instead of npm test, you can also
> run these other commands that are being run by CircleCI:
>
>
> https://github.com/bids-standard/bids-validator/blob/aa58a07258f398673cea98c041cd028f2a18b3fd/circle.yml#L17-L28
>
> Then at least you don't have to wait for Circle to build something 🤔
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bids-standard/bids-validator/pull/591#issuecomment-436944676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOkp72H5Xkif32JM_x-dEzAjGU2S2yrks5utAUfgaJpZM4W7l3M>
> .
>

2018-11-08 18:44 UTC, choldgraf commented
hey all - apparently @sappelhoff is a wizard and I owe him multiple beers

tests are passing

2018-11-09 18:49 UTC, sappelhoff commented
ready for a merge @choldgraf? I think the remaining point "Add a warning if people use a "supported but not recommended" format" might very well be its own PR

2018-11-09 18:53 UTC, choldgraf commented
I'm +1 on merge - I just opened https://github.com/bids-standard/bids-validator/issues/647 to keep track of the warning stuff.

I wouldn't be surprised if we need to iterate a bit more once people start trying out the new validator on their data, but we can do that in subsequent PRs.

2018-11-09 18:53 UTC, choldgraf commented
cc @dorahermes , who mentioned she wants to test out the validator on her data!

2018-11-09 19:54 UTC, dorahermes commented
would be good to have this included, will test extensively

2018-11-09 20:19 UTC, merged

2018-11-09 20:20 UTC, sappelhoff commented
perfect, thanks @choldgraf  for the PR and happy testing @dorahermes

2018-11-09 22:06 UTC, choldgraf commented
wooo, thanks for all the help!