Remote files validation
bids-standard/legacy-validator pull request #640
Opened 2018-10-31 20:49 UTC by olgn

refactor + improvements on #615. fixes #458.

* implements git-annex remote file access
* unit tests for utils/files/remoteFiles.js

2018-10-31 21:06 UTC, olgn commented
please ignore codeclimate telling me i have _too many tests_ *psh*

2018-10-31 21:53 UTC, nellh requested changes

2018-10-31 21:53 UTC, nellh commented on utils/files/__tests__/remoteFiles.spec.js
> +      child_process.execSync.mockReturnValue(new Buffer('test'))
Modifying this global will break other tests which use it.

2018-10-31 21:53 UTC, nellh commented on utils/files/remoteFiles.js
> +    git show git-annex:$(git-annex examinekey --json $(git-annex lookupkey ${relativePath}) | jq -r .hashdirlower)$(git-annex lookupkey ${relativePath}).log.rmet`
This should be split up so that it doesn't have external dependencies other than git-annex or depend on a specific shell, it was meant as an example of how to do this not the final implementation.

2018-10-31 21:53 UTC, nellh commented on utils/files/remoteFiles.js
> +  safeParse: function(string) {
This doesn't look like it's called anywhere? Maybe it can be eliminated.

2018-10-31 21:53 UTC, nellh commented on utils/files/remoteFiles.js
> +      return fetch(url).then(resp => resp.buffer())
s3.getObject and fetch work differently for HTTP error handling here. getObject will reject the promise if an HTTP error is encountered but fetch will resolve the promise. The fetch version needs a guard like this:

```javascript
fetch(url).then(resp => {
  if (resp.ok) {
    return resp.buffer()
  } else {
    return Promise.reject(
      new Error(`HTTP response failed - ${resp.status} - ${resp.statusText}`),
    )
  }
})
```

This will make them equivalent and avoid handling this in any callers.

2018-10-31 21:53 UTC, nellh commented on utils/files/remoteFiles.js
> +    Promise.all(
Nothing happens with this Promise.all call, so it's either not needed or not being returned properly.

2018-10-31 21:53 UTC, nellh commented on utils/files/__tests__/remoteFiles.spec.js
> +  describe('getAnnexedFile', () => {})
This is extra.

2018-10-31 21:53 UTC, nellh commented on utils/files/__tests__/remoteFiles.spec.js
> +      process.env.AWS_ACCESS_KEY_ID = 12
Might be good to reset proccess.env as well to avoid conflicts with other tests.

2018-10-31 21:53 UTC, nellh commented on utils/files/__tests__/remoteFiles.spec.js
> +      process.env.AWS_ACCESS_KEY_ID = 12
Oh, looks like it is done. But I think this should be handled with something like beforeEach and afterEach so that's clearly defined.

2018-11-01 17:24 UTC, olgn commented on utils/files/__tests__/remoteFiles.spec.js
> +      child_process.execSync.mockReturnValue(new Buffer('test'))
its also completely unnecessary -_-

2018-11-06 20:58 UTC, nellh commented on utils/files/__tests__/remoteFiles.spec.js
> +          new Promise(resolve => resolve({ ok: true, buffer: () => 'buffer' })),
This is equivalent to:

```javascript
() => Promise.resolve({ok: true, buffer: () => 'buffer'});
```

2018-11-06 20:58 UTC, nellh approved these changes

2018-11-07 18:15 UTC, merged