Error for empty files
bids-standard/legacy-validator pull request #645
Opened 2018-11-05 21:51 UTC by DaNish808

fix for issue #454

Notable changes: 
- added new error code 98: EMPTY_FILE
- added code to push error in testFile() (already called on config, bval, bvec, JSON, and tsv files)
- added misc group to files in fullTest to collect everything not run through testFile()
- added validateMisc(), which runs misc files through testFile()

2018-11-05 22:28 UTC, nellh requested changes
This should use a smaller example dataset or the test data should go in bids-examples, this adds a lot of files to the repo for one test suite.

2018-11-05 22:28 UTC, nellh commented on utils/files/testFile.js
> +                    }) not allowed; may corrupt archives.`,
The "may corrupt archives" part was due to a SciTran bug, not relevant to the validator.

2018-11-10 00:05 UTC, DaNish808 commented
working on merge conflict in testFile.js

2018-11-10 00:43 UTC, DaNish808 commented on utils/files/testFile.js
> +                    }) not allowed; may corrupt archives.`,
removed "may corrupt archives" and minimized test file

2018-11-11 20:59 UTC, nellh approved these changes

2018-11-12 17:41 UTC, merged