remove optional arguments bep006 and bep010
bids-standard/legacy-validator pull request #681
Opened 2019-01-11 11:07 UTC by sappelhoff

related to https://github.com/bids-standard/bids-specification/issues/107

this can be merged once https://github.com/bids-standard/bids-specification/issues/108 has been merged into the main BIDS specification.

2019-01-12 13:34 UTC, chrisfilo commented
What's the situation for test for those beps in the validator? Do they exist? HAve they been running in CI already?

2019-01-12 13:35 UTC, chrisgorgo requested changes

2019-01-12 13:35 UTC, chrisfilo commented on validators/bids/quickTest.js
> -const quickTest = (fileList, options) => {
I think instead of ripping this out it would be better to refactor it to easily enable future "work in progress" validator options related to BEP. This surely be needed in the future.

2019-01-14 08:30 UTC, sappelhoff commented
> What's the situation for test for those beps in the validator? Do they exist? Have they been running in CI already?

We have a comprehensive set of tests for both EEG and iEEG, see for example:

- https://github.com/bids-standard/bids-validator/blob/bdec39565eb13dab5e0dd6381975fac85020ec2a/tests/type.spec.js#L207-L279
- https://github.com/bids-standard/bids-validator/blob/57ee2a8e2273d3266ef77e8ffbaa5b9c88072a9f/tests/tsv.spec.js#L256-L436
- https://github.com/bids-standard/bids-validator/blob/bdec39565eb13dab5e0dd6381975fac85020ec2a/tests/json.spec.js#L74-L171

yes, they have been running in CI. With the `--bep` flags we only prevented a validator run to start if only the bep modalities are present ... in the tests however, we call functions directely, so the `--bep` flags do not have an influence on whether a test gets run or not (mostly)

2019-01-14 08:31 UTC, sappelhoff commented on validators/bids/quickTest.js
> -const quickTest = (fileList, options) => {
that is a good point. I'll make a suggestion that you can evaluate.

2019-01-14 09:23 UTC, sappelhoff commented on utils/type.js
> +      this.file.isEEG(path) ||
we'd have to insert some documentation that THIS is where the BEP flag should be, if somebody wants to add a new modality

2019-01-14 09:23 UTC, sappelhoff commented on utils/modalities.js
> +          isCorrectModality = !!options.bepWIP
instead of this "placeholder", we can also write the instructions into some documentation (see also comment below)

2019-01-14 09:24 UTC, sappelhoff commented
apart from the fact that `ES-lint` doesn't like my style (and neither does codeclimate) ( `67:26  error  'bepWIP' is defined but never used  no-unused-vars`) ... what do you think of this approach @chrisfilo ?

Do you have something different in mind?

2019-02-02 10:40 UTC, sappelhoff commented
looking back at this a few weeks later, it does not look nice at all. I am not sure about refactoring this structure of allowing BEP validation with the main validator.

I remember that we made this special case for EEG and iEEG because we had separate branches for them that were working nicely but then a major refactoring of the bids-validator which was supposed to happen at that time would have destroyed our work: that's why we integrated it into the main validator.

For future BEP validators I would recommend making a branch instead of this option feature that we have currently.

What do you think @chrisfilo ?

2019-02-21 19:58 UTC, chrisfilo commented
Could you rebase/merge master and make sure all the test pass? I hope we could merge this soon.

2019-02-22 13:47 UTC, sappelhoff commented
before doing more work on this, could you comment on what I wrote here: https://github.com/bids-standard/bids-validator/pull/681#issuecomment-459954799 ?

2019-02-22 16:11 UTC, chrisfilo commented
It's fine to remove optional validation functionality (that future beps could potentially benefit), if this is what you are asking. The valuator indeed went through a lot of changes.

2019-02-22 17:43 UTC, sappelhoff commented
I am not sure about that codeclimate issue, but these changes should suffice to make BEP006 and BEP010 part of the validator.

2019-02-22 17:45 UTC, chrisgorgo approved these changes

2019-02-22 17:47 UTC, chrisfilo commented
Thanks! Could you check the web version https://2255-37161308-gh.circle-artifacts.com/0/root/web_version/index.html against an example EEG dataset?

2019-02-23 07:38 UTC, sappelhoff commented
> Thanks! Could you check the web version https://2255-37161308-gh.circle-artifacts.com/0/root/web_version/index.html against an example EEG dataset?

done and it's looking good :+1:

the issue from #704 is also visible with the EEG data ... and /stimuli files also get listed as modalities

2019-02-25 08:18 UTC, sappelhoff commented
https://github.com/bids-standard/bids-specification/pull/108 has been merged, so this PR is ready to be merged as well :-)

:shipit:

2019-02-26 01:31 UTC, chrisfilo commented
will merge as soon as 1.2.0 is released - thank you for your hard work

2019-02-28 21:05 UTC, merged