DOC: add part on configs and improve formatting
bids-standard/legacy-validator pull request #700
Opened 2019-02-02 09:48 UTC by sappelhoff

related to https://github.com/bids-standard/bids-validator/issues/651#issuecomment-459911639

The addition to the documentation is rather minor:

```
For passing a configuration during javascript language use on the command line,
note that you **have to specify at least two configurations**, because an array
is expected. For example, the following code will ignore empty file errors (99)
and only warn about files that cannot be read (44):

    bids-validator --config.ignore=99 --config.warn=44 path/to/bids/dir

```

However I have also taken the chance to:
- break long lines
- declare the rendering of code blocks ... so now javascript object blocks have the correct syntax markup color

... hence the large diff although the addition is small.

2019-02-03 18:38 UTC, choldgraf commented
this seems good to me! looks like most of this is stylistic / line breaks / etc, which I think is great!

2019-02-04 22:56 UTC, nellh requested changes

2019-02-04 22:56 UTC, nellh commented on README.md
> +bids-validator --config.ignore=99 --config.warn=44 path/to/bids/dir
This is slightly incorrect, it has to be two of the same key for the configuration items which accept array arguments. E.g. `--config.ignore --config.ignore` not `--config.ignore --config.warn`

2019-02-05 08:00 UTC, sappelhoff commented on README.md
> +bids-validator --config.ignore=99 --config.warn=44 path/to/bids/dir
Thanks @nellh, I changed it.

2019-02-05 17:01 UTC, merged