Update MEG regexp
bids-standard/legacy-validator pull request #789
Opened 2019-06-21 12:07 UTC by sappelhoff

In this PR I add to the MEG regexp so that `_markers.<sqd, con>)` can be accepted, as well as general MEG data files in the KIT format ending either with `.sqd` or `.con`.

This is BIDS since these PRs:
- https://github.com/bids-standard/bids-specification/pull/19
- https://github.com/bids-standard/bids-specification/pull/62

I furthermore update the `yarn.lock` file to include the hed validator, which has recently been added (but no to the lock file yet)

This is based on a use case, where the validator throws an error for a correct KIT BIDS dataset, see: https://github.com/mne-tools/mne-bids/pull/209#issuecomment-504356977

# Interesting observations (i.e., I don't know what's happening and why)

- the error based on the use case did only show up for the recent validator version `1.2.4` ... but not for previous versions. Yet, I cannot find any commit leading up to `1.2.4` that should have changed the way the validator looks at MEG files ...
- for the MEG regexp, looking at this line: https://github.com/bids-standard/bids-validator/blob/e3c6e4635f077d4b01e7c13baee4a0cf44199c69/bids-validator/bids_validator/rules/file_level_rules.json#L203

--> when I added my addition: `"\\.(?:sqd|con)"` to the END of the line ... it did not work (i.e., did not resolve the use case error) ... however, adding it to the MIDDLE, or the START of the line did work - without breaking any tests.

- works: `["\\.(?:sqd|con)", "\\.fif", "\\.ds"]`
- works: `["\\.fif", "\\.(?:sqd|con)", "\\.ds"]`
- does NOT work: `["\\.fif", "\\.ds", "\\.(?:sqd|con)"]`

Can somebody shed some light on this?

2019-06-21 14:43 UTC, jasmainak commented
> Yet, I cannot find any commit leading up to 1.2.4 that should have changed the way the validator looks at MEG files ...

you can try "git bisect" on a local version of the validator to figure out what leads to the problem

2019-06-21 14:45 UTC, jasmainak commented
> Can somebody shed some light on this?

I usually use https://regex101.com/ for these kinds of things ... :-)

2019-06-21 14:46 UTC, jasmainak reviewed
my usual comment. Can you add a test? ;-)

2019-06-21 14:46 UTC, sappelhoff commented
> I usually use https://regex101.com/ for these kinds of things ... :-)

me too ... but for that specific case, it's a JS array with several strings that just get inserted into the regexp --> so the order of items in this array should not make a difference

2019-06-21 15:12 UTC, sappelhoff commented
> you can try "git bisect" on a local version of the validator to figure out what leads to the problem

[git bisect](https://git-scm.com/docs/git-bisect) seems super cool! ... I couldn't use it properly though, for the following puzzling reason:

1. Using the LOCAL validator version ... the use case of [`test_kit`](https://github.com/mne-tools/mne-bids/blob/a1f3288871eea49cfdaead0b20000570044fc62b/mne_bids/tests/test_write.py#L184) ALWAYS fails (regardless of version)
    - note, I was using `git checkout 1.2.3` or `git checkout 1.2.4`
2. However, using the GLOBAL (`npm i -g bids-validator@1.2.4`) validator version, `test_kit` fails only for version `1.2.4`, but not when doing `npm i -g bids-validator@1.2.4` right before ...

2019-06-21 15:42 UTC, jasmainak commented
sounds like some packaging issue, but I'm not a javascript expert ...

2019-06-21 15:42 UTC, jasmainak commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
can you add an example to badFilenames? E.g., something with a father level directory should fail

2019-06-21 15:48 UTC, sappelhoff commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
Mmh currently the validator provides a wildcard for everything that is within a father level directory, see: https://github.com/bids-standard/bids-validator/blob/e3c6e4635f077d4b01e7c13baee4a0cf44199c69/bids-validator/bids_validator/rules/file_level_rules.json#L201

the final part is the relevant one: `?(_meg(@@@_meg_type_@@@\\/.*|\\/.*)|`

- it will try to match either an `meg_type`
    - these are defined below: `"@@@_meg_type_@@@": ["\\.fif", "\\.ds"],`
- or it will match a father level directory with arbitrary contents: `|\\/.*`

for a test that you suggest I would have to touch this logic ... which could have unforeseen consequences.

Two options:
1. make an issue and let some regex/JS expert deal with this
2. I try to do it

2019-06-22 12:09 UTC, jasmainak commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
I would say if the tests pass, you should be fairly confident of your change. Any unforeseen consequences can be dealt with in the future by adding more tests (and thus increasing your confidence even more in subsequent changes!)

What file formats still allow father level directories? It's only CTF with the *.ds format, right? There are a bunch of tests which need to be updated to reflect this, no? I'll comment on the relevant part.

2019-06-22 12:10 UTC, jasmainak commented on bids-validator/tests/type.spec.js
>      '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/sub-01_ses-001_markers.sqd',
is this still a good file name?

2019-06-22 12:13 UTC, jasmainak commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
> or it will match a father level directory with arbitrary contents:

I seem to remember there was a reason for allowing arbitrary contents. See the discussion in my old PR here: https://github.com/bids-standard/bids-validator/pull/499

2019-06-24 08:24 UTC, robertoostenveld commented on bids-validator/tests/type.spec.js
>      '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/sub-01_ses-001_markers.sqd',
I think that 

```
/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/abc.raw
/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/abc.raw.mhd
/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-02_meg/def.sqd
/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-03_meg/ghi
```

are all good names for directory+file. The reason for the father directory `sub-01_ses-001_task-rest_run-01_meg` is to *not* require changes to the actual file names. So the files underneath can be called whatever, as long as those are known MEG files and can be processed in the software of the original MEG system manufacturer (i.e. BTi, KIT, ITAB). 

It would be good to determine the allowed file names and/or extensions for the different systems. I suspect that https://github.com/fieldtrip/fieldtrip/blob/master/fileio/ft_filetype.m has quite a few of them.

2019-06-24 08:57 UTC, sappelhoff commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
MEG file formats with father level according to the [latest](https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html) spec:
- CTF
- BTi/4D (why does this one have two names, BTW?)

2019-06-24 09:01 UTC, sappelhoff commented on bids-validator/tests/type.spec.js
>      '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/sub-01_ses-001_markers.sqd',
I agree with @robertoostenveld :

> So the files underneath can be called whatever, **as long as** those are known MEG files and can be processed in the software of the original MEG system manufacturer [emphasis added by @sappelhoff]

--> I think what @jasmainak wants is that we add tests for exactly that: I.e., do NOT accept whatever file underneath ... but instead only accept those files underneath from which we know that they are correctly there. E.g., CTF and BTi/4D (these are the only MEG data formats that have a father format, see my [comment](https://github.com/bids-standard/bids-validator/pull/789#discussion_r296618524))

I think I generally agree with what @jasmainak says, but I could also imagine this in a separate PR, because it goes beyond the scope of this PR, which was the following:

- Allow that KIT data is specified without father level, because it does not need one anymore (according to latest spec)
- Add tests that pass with KIT data specified without father level

2019-06-24 09:57 UTC, robertoostenveld commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_meg.con', // KIT with removed father level directory
The initial company in San Diego that commercially developed MEG was called "BTi", which is probably an abbreviation . Later they were renamed into "4-D Neuroimaging", which is usually abbreviated (by me) as "4D".

2019-06-24 09:59 UTC, robertoostenveld commented on bids-validator/tests/type.spec.js
>      '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/sub-01_ses-001_markers.sqd',
agreed that we should keep the PR focussed on one aspect, which is KIT.

2019-06-24 13:45 UTC, jasmainak commented on bids-validator/tests/type.spec.js
>      '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg/sub-01_ses-001_markers.sqd',
If you want to do it in another PR that's fine but my comment above was for the KIT .sqd file, not the others :) Let's raise an issue so we don't forget.

2019-06-24 17:27 UTC, sappelhoff commented
@robertoostenveld @jasmainak 

I ended up revamping the test suite for all MEG data. Please check if you agree with this.

Father levels are only present for
- BTI
- CTF

The other 4 file formats do NOT have a father level anymore:
- FIF
- KRISS
- KIT
- ITAB

2019-06-24 17:39 UTC, jasmainak commented
I did not check if the file formats with or without father level are correct or not. But the tests look good to me

2019-06-25 06:55 UTC, robertoostenveld requested changes

2019-06-25 06:55 UTC, robertoostenveld commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg.ds/catch-alp-good-f.meg4',
the contents within the CTF `.ds` must be checked, otherwise it is not a valid dataset and standard software (e..g that of CTF itself) will not be able to read it.

2019-06-25 07:29 UTC, sappelhoff commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg.ds/catch-alp-good-f.meg4',
I agree, but this is not something I break in this PR ... it's never been there :-)

Also, I have opened an issue on this several months ago: https://github.com/bids-standard/bids-validator/issues/692

2019-06-25 07:55 UTC, robertoostenveld commented on bids-validator/tests/type.spec.js
> +    '/sub-01/ses-001/meg/sub-01_ses-001_task-rest_run-01_meg.ds/catch-alp-good-f.meg4',
agreed

2019-06-25 07:55 UTC, robertoostenveld approved these changes

2019-06-25 11:03 UTC, sappelhoff commented
merging after approval by Mainak and Robert. Thanks for the reviews!

2019-06-25 11:03 UTC, merged