lerna versioning
bids-standard/legacy-validator pull request #797
Opened 2019-07-09 22:29 UTC by DaNish808

Introduces [Lerna](https://github.com/lerna/lerna) to maintain the version numbers for the bids-validator and bids-validator-web packages separately and within their package.json files (should resolve #602).

Publish a new version with `yarn lerna publish` and follow instructions to set major/minor/patch updates.

2019-07-09 22:35 UTC, nellh requested changes
The documentation needs to be updated to include info on Lerna (at least a link to it) and document how to do a release.

2019-07-10 07:53 UTC, sappelhoff commented on bids-validator/README.md
> +#### Publishing
is publishing used synonymously with "making a release" here?

2019-07-10 16:57 UTC, nellh commented on bids-validator/README.md
> +#### Publishing
Using `lerna publish` will create a git commit with updated version information and create a version number tag for it, push the tag to GitHub, then publish to NPM and PyPI. The GitHub release is manual following that.

2019-07-10 16:59 UTC, sappelhoff commented on bids-validator/README.md
> +#### Publishing
Okay :+1: thanks for clarifying! Perhaps we could add exactly that information.

2019-07-12 16:31 UTC, nellh approved these changes

2019-07-12 16:34 UTC, rwblair approved these changes

2019-07-12 16:37 UTC, merged