add info about squishymedia
bids-standard/legacy-validator pull request #798
Opened 2019-07-10 09:22 UTC by sappelhoff

related to discussion on BIDS governance, see: https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit?disco=AAAADI0g6l4

cc @effigies @franklin-feingold @yarikoptic 

Please advise on the wording.

2019-07-10 12:31 UTC, effigies commented
Russ' name is spelled wrong, but this otherwise seems fine.

2019-07-10 13:58 UTC, yarikoptic requested changes
I more often hear use of "supported" as in money in such context, so I would have used "done" or alike. Also a dedicated Acknowledgments section would be more appropriate place.

2019-07-10 14:03 UTC, effigies commented on bids-validator/README.md
> +[squishymedia](https://squishymedia.com/), who are in turn financed by a grant
```suggestion
[Squishymedia](https://squishymedia.com/), who are in turn financed by a grant
```

2019-07-11 08:39 UTC, sappelhoff commented
After discussion on Slack, we agreed that it's probably a good idea to ask each PI with a grant for BIDS-related activities whether they want to be listed here.

@yarikoptic @satra 

@effigies perhaps you can tag some other people that you know of.

@franklin-feingold the formatting of Russ' grants is as you told me over Slack. But perhaps you could provide the more formal version of it?

Currently it's looking like this:

```
- BIDS R24,
- OpenNeuro R24
- NSF Spokes grant
```

2019-07-11 18:51 UTC, franklin-feingold commented
the more formal/detailed version of our grants that I know of supporting squishy:
- [Brain Imaging Data Structure (BIDS) Derivatives grant funded by the NIMH: R24MH114705](http://grantome.com/grant/NIH/R24-MH114705-01) (PI: Poldrack)
- [OpenNeuro grant funded by the NIMH: R24MH117179](http://grantome.com/grant/NIH/R24-MH117179-01) (PI: Poldrack)
- [Spokes: MEDIUM: WEST grant funded by the NSF: 1760950](http://grantome.com/grant/NSF/IIS-1760950) (PI: Poldrack & Gorgolewski)

2019-07-11 20:57 UTC, yarikoptic commented
So it could look like
```markdown
Development and contributions were supported through following federally funded projects/grants
- [BIDS Derivatives (NIMH: R24MH114705, PI: Poldrack)](http://grantome.com/grant/NIH/R24-MH114705-01)
- ...
```
rendered as

Development and contributions were supported through following federally funded projects/grants
- [BIDS Derivatives (NIMH: R24MH114705, PI: Poldrack)](http://grantome.com/grant/NIH/R24-MH114705-01)
- ...

and so on.  You could add

```markdown
- [ReproNim](http://repronim.org) ([NIH-NIBIB P41 EB019936, PI: Kennedy](https://projectreporter.nih.gov/project_info_description.cfm?aid=8999833))
```

2019-07-12 08:03 UTC, sappelhoff commented
great, thanks for your help @yarikoptic and @franklin-feingold! Ready for a review

2019-07-12 17:53 UTC, franklin-feingold approved these changes

2019-07-12 17:58 UTC, effigies approved these changes
LGTM. I put this below the new publish section from #797.

2019-07-16 19:43 UTC, merged