[WIP] 818 gitTreeMode
bids-standard/legacy-validator pull request #833
Opened 2019-09-16 16:28 UTC by DaNish808

Adds the gitTreeMode option.
- [x] bids-validator run on a git-annexed dataset in gitTreeMode will use the git annex metadata to read the directory and extract file size and path information, skipping fs calls.
- [x] all tests in bids.spec run again with gitTreeMode on

2019-09-16 16:34 UTC, nellh commented on bids-validator/bin/bids-validator
> +  })
This could be one option, gitRef implies the other option.

2019-09-16 16:42 UTC, nellh commented on bids-validator/utils/files/readDir.js
> +  const shaObj = new jsSHA('SHA-1', 'TEXT')
Since this feature is only useful in Node.js, we should use the Node API instead of a JS implementation. https://nodejs.org/api/crypto.html

2019-09-17 21:05 UTC, DaNish808 commented on bids-validator/bin/bids-validator
> +  })
I think that if we want gitRef to default to 'HEAD'  it makes sense to leave both in, since most use cases will just want the boolean option. Or we could remove 'HEAD' as the default ref.

2019-09-17 23:19 UTC, nellh commented on bids-validator/bin/bids-validator
> +  })
I took a look at yargs and it doesn't support the kind of option parsing that would allow this, so it does make sense to keep both. How about adding [implies](https://yargs.js.org/docs/#api-impliesx-y) so that it throws an error if only gitRef is set?

2019-09-18 17:20 UTC, nellh requested changes
I tried running this on a dataset downloaded from OpenNeuro via DataLad and I get different validation results with and without the gitTreeMode flag. Here's the extra error output and I invoked this with `bids-validator --gitTreeMode /home/nell/ds001769`.

```
	1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_componentLabels.txt
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_componentLabels.txt
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_components.nii.gz
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_components.nii.gz
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_decomposition.json
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_decomposition.json
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_mixing.tsv
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-MELODIC_mixing.tsv
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-denoised_bold.json
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-denoised_bold.json
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-denoised_bold.nii.gz
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-sm5_desc-denoised_bold.nii.gz
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_componentLabels.txt
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_componentLabels.txt
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_components.nii.gz
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_components.nii.gz
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_decomposition.json
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_decomposition.json
		./sub-01/ses-movie/func/sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_mixing.tsv
			Evidence: sub-01_ses-movie_task-movie_run-1_space-T1w_desc-preproc_desc-unsm_desc-MELODIC_mixing.tsv
		... and 1430 more files having this issue (Use --verbose to see them all).

	Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

	2: [ERR] No BIDS compatible data found for at least one subject. (code: 67 - NO_VALID_DATA_FOUND_FOR_SUBJECT)
		./sub-01
		./sub-02
		./sub-03
		./sub-04
		./sub-05
		./sub-06
		./sub-09
		./sub-10
		./sub-14
		./sub-15
		... and 5 more files having this issue (Use --verbose to see them all).
```

2019-09-18 21:01 UTC, nellh approved these changes

2019-09-18 21:02 UTC, merged