623 tsv helper function
bids-standard/legacy-validator pull request #887
Opened 2019-12-09 20:47 UTC by MatthewZito

2019-12-09 21:15 UTC, effigies commented
Ref: #623

2019-12-13 22:18 UTC, david-nishi requested changes

2019-12-13 22:18 UTC, david-nishi commented on bids-validator/validators/tsv/tsvParser.js
> +function ParseTSV(contents) {
Let's switch to camelCase for function and variable names.

2019-12-13 22:18 UTC, david-nishi commented on bids-validator/validators/tsv/tsvParser.js
> +  }
We should refactor this loop for clarity. There are some unused variables and and a leftover conditional statement.

2019-12-13 22:18 UTC, david-nishi commented on bids-validator/validators/tsv/tsv.js
> +    var row = rows[i]
row is used for evidence, so I think we should be setting this to something more informative. Maybe `row ${i}: ${values.join('\t')}`

2019-12-16 19:04 UTC, david-nishi approved these changes

2019-12-17 17:41 UTC, nellh requested changes
Took a quick look before merging this and there's still one issue I think should be fixed before merge, the mixed export styles should be ES6 exports. We've switched away from CJS in #864

2019-12-17 17:41 UTC, nellh commented on bids-validator/validators/tsv/tsvParser.js
> +module.exports = parseTSV
This should be an ES6 export.

2019-12-17 17:41 UTC, nellh commented on bids-validator/validators/bids/fullTest.js
> +  let phenotypeParticipants = []
These should all be `const`.

2019-12-17 17:41 UTC, nellh commented on bids-validator/validators/tsv/tsvParser.js
> +  }
This should also be `const`.

2019-12-17 19:39 UTC, merged