[MRG]
bids-standard/legacy-validator pull request #976
Opened 2020-06-12 14:30 UTC by adam2392

Closes: #971 

Add an error message to validator if the `scans.tsv` does not match the actual files listed for that subject.

2020-06-20 02:20 UTC, adam2392 commented
@rwblair I read through the `CONTRIBUTING.md` file, but I am not very experienced w/ JS. Is there a general workflow for testing changes locally that I can do to get a better handle on why the pushed changes are failing?

Appreciate any assistance you can give me!

2020-06-20 07:34 UTC, sappelhoff commented
Hey @adam2392 have you had a try at the following two sections?

1. install dev version of validator: [link](https://github.com/bids-standard/bids-validator/blob/master/CONTRIBUTING.md#using-the-development-version-of-bids-validator)
1. testing section of the README: https://github.com/bids-standard/bids-validator#testing

where are you stuck exactly?

2020-06-21 03:03 UTC, adam2392 commented
> 1. link

Okay got it setup! I missed that section on testing, but it is pretty nicely documented and got me in the right path to refresh my javascript. So now I am looking at 3 files and working thru the following changes:

1. tsv.js: This file needs to pull the filenames from the scans.tsv and loop through them and check if each one is in the `fileList`. This `fileList` variable seems to store the full file path for all the files inside the relative scans path (e.g. `<sub>/<ses>/func/`). So all we need to do is check the relative path of each filename for existence. 

However, we also want to check if all the fileList is accounted for as well? That is, if there are 3 datasets, but only 2 filenames inside scans.tsv. Any suggestion on how to do this part? Should I convert `fileList` to a javascript "hash map"?

2. tsv.spec.js: This test file needs a few changes I think (https://github.com/bids-standard/bids-validator/blob/8891c2978c41aeac28d89324baadc9b5be76365b/bids-validator/tests/tsv.spec.js#L154-L197)(?) Asking to make sure this is the right changes to be made. 

To test what we want, we need to add some fake filepaths into the `<sub>/<ses>/func/` directory, instead of the `value-one` that's being added currently. For example:

```Javascript
  var niftiFile = {
    name: 'sub-08_ses-test_task-linebisection_run-01_bold.nii.gz',
    relativePath:
      '/sub-08/ses-test/func/'
  }
```

3. list.js: I have added a new issue # 129 for if the scans.tsv `filename` column does not match what is actually inside bids root. I think this is valid.

2020-06-22 21:40 UTC, rwblair commented
@adam2392 Amazing work, thank you so much. I had one specific comment on the code that I left in the review.

To touch on one point:

> However, we also want to check if all the fileList is accounted for as well? That is, if there are 3 datasets, but only 2 filenames inside scans.tsv. Any suggestion on how to do this part? Should I convert `fileList` to a javascript "hash map"?

This becomes much more difficult. It would need to take place in a slightly different place in the validator. One way would be to collect all the filenames referenced in across all scans.tsv files and then check against fileList. We are doing something like this with participants. For each we file we make a list of participants:

https://github.com/bids-standard/bids-validator/blob/f9fdd426245a0feb2cc1dd53d9ce3915c3517270/bids-validator/validators/tsv/tsv.js#L217

Then pass it to the callback that appears in tsv.validate:
https://github.com/bids-standard/bids-validator/blob/f9fdd426245a0feb2cc1dd53d9ce3915c3517270/bids-validator/validators/tsv/tsv.js#L352

Now being called participantList:
https://github.com/bids-standard/bids-validator/blob/f9fdd426245a0feb2cc1dd53d9ce3915c3517270/bids-validator/validators/tsv/validate.js#L37

Do we need to do this check at all? The spec states:

> Each .nii[.gz] file should be described by at most one row. 
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file

So that's not great since it can be applied to things other than nifti files. @sappelhoff how do you read that? Should we issue a warning if some file isn't present in a scans.tsv but other files of the same type are?

2020-06-22 21:49 UTC, rwblair requested changes

2020-06-22 21:49 UTC, rwblair commented on bids-validator/validators/tsv/tsv.js
> +        if (!(scanFullPath in pathList)) {
I had to change this to be `pathList.includes(scanFullPath)` instead of `scanFullPath in pathList`. The `in` operator in javascript is not as robust as python, used for seeing if a property or key is present in an object.

2020-06-23 00:39 UTC, adam2392 commented
@rwblair awesome, I added some fixes and it will now fire an error if the scans listed in the scans.tsv file are not found in the `pathList`.

I don't really understand what is going on in `validate.js` where you link the callback. I don't get how the participants is even being used there? Why can't we just check within each `scans.tsv`, the files listed in the scans.tsv file against the `pathList` variable in `tsv.js`?

^ If that is up for discussion, we can also move that to a future PR?

2020-06-23 00:40 UTC, adam2392 commented
I also don't know why the circleci test is still failing? My local version seems working when I run:

`npm test`

2020-06-23 08:12 UTC, sappelhoff commented
>  Should we issue a warning if some file isn't present in a scans.tsv but other files of the same type are?

not sure what you mean by that, but I think @adam2392's proposal is reasonable.

with this PR we check that a given SCANS file does not contain rows referring to non-existing data.

as a next step we should check that IF a scans file exists, it should be complete. --> but as I read from your posts it seems to be difficult to:

- collect all scans files (either nii.gz, or .fif., or a vhdr+eeg+vmrk triplet, or a .ds directory, ...)  at a subj/session level
- check that IF a scans.tsv file exist, all of the scans files are entered in there

I think the fact that some data formats have "scans" consisting out of one file, yet other consist our of three files, or even a directory does not make this easier.

Would be fine with me to do this in a separate PR.

2020-06-23 15:50 UTC, rwblair commented
Builds failling was because the valid test dataset was using .nii.gz for filenames in scans.tsv while the actual files were only .nii.

I'm going to close #971 since this addresses the original concern in it and open a new issue for the expanded verification that any file that should be mentioned in a scans file is mentioned in one.

2020-06-23 15:54 UTC, merged

2020-06-23 17:31 UTC, sappelhoff commented
Thanks ross and adam!

2020-06-23 20:34 UTC, jasmainak commented
excellent stuff @adam2392 . Looking for more folks with experience on all aspects of the BIDS vertical :)

2020-06-28 16:41 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
> +var path = require('path');
Looks like this isn't used and it should be `import path from 'path'` if it was. This is a Node.js module as well, care needs to be take to avoid importing Node.js modules in code that runs in browser environments.

2020-06-28 17:24 UTC, nellh commented on bids-validator/validators/tsv/tsv.js
> +var path = require('path');
`path` specifically is working though, we are pulling in path-browserify somewhere down the dependency chain for the web validator and OpenNeuro. We might want to make path-browserify a dependency of bids-validator make sure it is always available. Or choose a portable path manipulation library and use that.

2020-06-29 13:44 UTC, rwblair commented on bids-validator/validators/tsv/tsv.js
> +var path = require('path');
Looks like path-browserify is included by default in webpack and browserify, but I think adding it as a dependency is fine since something like this might change without warning.